# Generated by Django 4.2.22 on 2026-06-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0005_alter_configuration_white_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyEngineConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "policyengine_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Pinned PolicyEngine package version sent as the top-level "version" field, e.g. "1.715.2" (must be an exact MAJOR.MINOR.PATCH number). Clear this field (leave blank) and save to fall back to PolicyEngine\'s default. The floating aliases "frontier" / "current" are not allowed here.',
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "PolicyEngine Version",
                "verbose_name_plural": "PolicyEngine Version",
            },
        ),
    ]
