# Generated by Django 4.2.22 on 2026-06-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0006_policyengineconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policyengineconfig",
            options={"verbose_name": "PolicyEngine Version", "verbose_name_plural": "PolicyEngine Version"},
        ),
    ]
