from .base import ConfigurationData
from screener.models import WhiteLabel


class KsConfigurationData(ConfigurationData):
    @classmethod
    def get_white_label(self) -> WhiteLabel:
        return WhiteLabel.objects.get(code="ks")

    # ==========================================================================================
    # BASIC INFORMATION
    # ==========================================================================================

    # Offered in the public state dropdown.
    publicly_launched = True

    state = {"name": "Kansas"}

    public_charge_rule = {
        "link": "https://www.uscis.gov/green-card/green-card-processes-and-procedures/public-charge",
        "text": {
            "_label": "landingPage.publicChargeLinkKS",
            "_default_message": "U.S. Citizenship and Immigration Services",
        },
    }

    more_help_options = {
        "moreHelpOptions": [
            {
                "name": {
                    "_default_message": "Kansas 211 (United Way of Kansas)",
                    "_label": "moreHelp.211.name.ks",
                },
                "link": "https://unitedwayplains.org/211-information-and-referral/",
                "phone": {
                    "_default_message": "Dial 2-1-1",
                    "_label": "moreHelp.211.phone.ks",
                },
            },
        ]
    }

    # ==========================================================================================
    # IMMEDIATE NEED OPTIONS
    # Base options plus three tiles the base set doesn't offer:
    #   freeLowCostMedicalCare - base only has dental care, leaving community health centers
    #                            with nowhere to surface
    #   savings                - reuses Screen.needs_college_savings (as CO does), but labelled
    #                            broadly rather than CO's college-specific wording
    #   transportation         - new Screen.needs_transportation field
    # ==========================================================================================

    acute_condition_options = {
        **ConfigurationData.acute_condition_options,
        "freeLowCostMedicalCare": {
            "icon": {"_icon": "Health_care", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.freeLowCostMedicalCare",
                "_default_message": "Free or lower cost health care",
            },
        },
        "savings": {
            "icon": {"_icon": "Savings", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.savings.ks",
                "_default_message": "Savings",
            },
        },
        "transportation": {
            "icon": {"_icon": "Transportation", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.transportation",
                "_default_message": "Transportation",
            },
        },
    }

    # ==========================================================================================
    # HEALTH INSURANCE OPTIONS
    # Kansas Medicaid is branded "KanCare"
    # ==========================================================================================

    health_insurance_options = {
        "you": {
            **ConfigurationData.health_insurance_options["you"],
            "medicaid": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicaid.ks",
                    "_default_message": "KanCare (Medicaid)",
                },
            },
            "chp": {
                "icon": {"_icon": "Chp", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.chp.ks",
                    "_default_message": "KanCare (CHIP)",
                },
            },
        },
        "them": {
            **ConfigurationData.health_insurance_options["them"],
            "medicaid": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicaid.ks",
                    "_default_message": "KanCare (Medicaid)",
                },
            },
            "chp": {
                "icon": {"_icon": "Chp", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.chp.ks",
                    "_default_message": "KanCare (CHIP)",
                },
            },
        },
    }

    # ==========================================================================================
    # COUNTIES BY ZIPCODE
    # Source: HUD USPS ZIP-County crosswalk, **2026 Q2** (file ZIP-COUNTY_062026.xlsx),
    #   downloaded from https://www.huduser.gov/apps/public/uspscrosswalk/login
    # County names come from HUD fmr/listCounties/{state} (year=2025&updated=2025), except
    #   29510, which we spell "St. Louis City" -- PolicyEngine's independent-cities token
    #   depends on that exact string.
    # Each zip keeps every county with a nonzero residential share (res_ratio > 0), ordered by
    #   descending res_ratio so the likeliest county is first in the dropdown. A business-only
    #   zip (res_ratio 0 for every county) keeps all its counties, ordered by tot_ratio, so no
    #   zip is dropped.
    # Regenerate with generate_ks_mo_zip_county_maps.py when a newer vintage is published.
    # ==========================================================================================
    counties_by_zipcode = {
        "66002": {
            "Atchison County": "Atchison County",
            "Doniphan County": "Doniphan County",
            "Jefferson County": "Jefferson County",
            "Leavenworth County": "Leavenworth County",
        },
        "66006": {"Douglas County": "Douglas County", "Franklin County": "Franklin County"},
        "66007": {"Leavenworth County": "Leavenworth County", "Wyandotte County": "Wyandotte County"},
        "66008": {"Doniphan County": "Doniphan County"},
        "66010": {
            "Linn County": "Linn County",
            "Bourbon County": "Bourbon County",
            "Anderson County": "Anderson County",
        },
        "66012": {"Wyandotte County": "Wyandotte County", "Leavenworth County": "Leavenworth County"},
        "66013": {"Johnson County": "Johnson County", "Miami County": "Miami County"},
        "66014": {"Linn County": "Linn County", "Anderson County": "Anderson County"},
        "66015": {"Anderson County": "Anderson County", "Allen County": "Allen County"},
        "66016": {"Atchison County": "Atchison County"},
        "66017": {"Doniphan County": "Doniphan County", "Brown County": "Brown County"},
        "66018": {"Johnson County": "Johnson County"},
        "66020": {"Leavenworth County": "Leavenworth County"},
        "66021": {
            "Johnson County": "Johnson County",
            "Miami County": "Miami County",
            "Douglas County": "Douglas County",
        },
        "66023": {"Atchison County": "Atchison County"},
        "66024": {"Doniphan County": "Doniphan County"},
        "66025": {"Douglas County": "Douglas County", "Johnson County": "Johnson County"},
        "66026": {"Miami County": "Miami County", "Linn County": "Linn County"},
        "66027": {"Leavenworth County": "Leavenworth County"},
        "66030": {"Johnson County": "Johnson County", "Miami County": "Miami County"},
        "66031": {"Johnson County": "Johnson County"},
        "66032": {"Anderson County": "Anderson County"},
        "66033": {
            "Anderson County": "Anderson County",
            "Franklin County": "Franklin County",
            "Linn County": "Linn County",
        },
        "66035": {"Doniphan County": "Doniphan County"},
        "66036": {"Miami County": "Miami County"},
        "66039": {"Anderson County": "Anderson County", "Allen County": "Allen County", "Linn County": "Linn County"},
        "66040": {"Linn County": "Linn County", "Miami County": "Miami County"},
        "66041": {
            "Atchison County": "Atchison County",
            "Doniphan County": "Doniphan County",
            "Brown County": "Brown County",
        },
        "66042": {"Franklin County": "Franklin County", "Miami County": "Miami County", "Linn County": "Linn County"},
        "66043": {"Leavenworth County": "Leavenworth County"},
        "66044": {
            "Douglas County": "Douglas County",
            "Leavenworth County": "Leavenworth County",
            "Jefferson County": "Jefferson County",
        },
        "66045": {"Douglas County": "Douglas County"},
        "66046": {"Douglas County": "Douglas County"},
        "66047": {"Douglas County": "Douglas County"},
        "66048": {"Leavenworth County": "Leavenworth County", "Wyandotte County": "Wyandotte County"},
        "66049": {"Douglas County": "Douglas County"},
        "66050": {"Douglas County": "Douglas County", "Shawnee County": "Shawnee County"},
        "66051": {"Johnson County": "Johnson County"},
        "66052": {"Leavenworth County": "Leavenworth County"},
        "66053": {"Miami County": "Miami County"},
        "66054": {"Jefferson County": "Jefferson County", "Leavenworth County": "Leavenworth County"},
        "66056": {"Linn County": "Linn County", "Bourbon County": "Bourbon County"},
        "66058": {"Atchison County": "Atchison County", "Jackson County": "Jackson County"},
        "66060": {"Jefferson County": "Jefferson County", "Atchison County": "Atchison County"},
        "66061": {"Johnson County": "Johnson County"},
        "66062": {"Johnson County": "Johnson County"},
        "66063": {"Johnson County": "Johnson County"},
        "66064": {"Miami County": "Miami County", "Franklin County": "Franklin County", "Linn County": "Linn County"},
        "66066": {"Jefferson County": "Jefferson County"},
        "66067": {"Franklin County": "Franklin County"},
        "66070": {"Jefferson County": "Jefferson County"},
        "66071": {"Miami County": "Miami County"},
        "66072": {"Linn County": "Linn County", "Miami County": "Miami County"},
        "66073": {"Jefferson County": "Jefferson County"},
        "66075": {"Linn County": "Linn County"},
        "66076": {"Franklin County": "Franklin County"},
        "66078": {"Franklin County": "Franklin County"},
        "66079": {"Franklin County": "Franklin County", "Miami County": "Miami County"},
        "66080": {"Franklin County": "Franklin County", "Anderson County": "Anderson County"},
        "66083": {"Johnson County": "Johnson County", "Miami County": "Miami County"},
        "66085": {"Johnson County": "Johnson County"},
        "66086": {"Leavenworth County": "Leavenworth County", "Jefferson County": "Jefferson County"},
        "66087": {"Doniphan County": "Doniphan County"},
        "66088": {"Jefferson County": "Jefferson County", "Atchison County": "Atchison County"},
        "66090": {"Doniphan County": "Doniphan County"},
        "66091": {"Anderson County": "Anderson County"},
        "66092": {
            "Franklin County": "Franklin County",
            "Miami County": "Miami County",
            "Douglas County": "Douglas County",
        },
        "66093": {"Anderson County": "Anderson County", "Coffey County": "Coffey County"},
        "66094": {"Doniphan County": "Doniphan County", "Brown County": "Brown County"},
        "66095": {
            "Franklin County": "Franklin County",
            "Anderson County": "Anderson County",
            "Osage County": "Osage County",
            "Coffey County": "Coffey County",
        },
        "66097": {"Jefferson County": "Jefferson County", "Leavenworth County": "Leavenworth County"},
        "66101": {"Wyandotte County": "Wyandotte County"},
        "66102": {"Wyandotte County": "Wyandotte County"},
        "66103": {"Wyandotte County": "Wyandotte County"},
        "66104": {"Wyandotte County": "Wyandotte County"},
        "66105": {"Wyandotte County": "Wyandotte County"},
        "66106": {"Wyandotte County": "Wyandotte County"},
        "66109": {"Wyandotte County": "Wyandotte County", "Leavenworth County": "Leavenworth County"},
        "66110": {"Wyandotte County": "Wyandotte County"},
        "66111": {"Wyandotte County": "Wyandotte County"},
        "66112": {"Wyandotte County": "Wyandotte County"},
        "66113": {"Wyandotte County": "Wyandotte County"},
        "66115": {"Wyandotte County": "Wyandotte County"},
        "66117": {"Wyandotte County": "Wyandotte County"},
        "66118": {"Wyandotte County": "Wyandotte County"},
        "66119": {"Wyandotte County": "Wyandotte County"},
        "66160": {"Wyandotte County": "Wyandotte County"},
        "66201": {"Johnson County": "Johnson County"},
        "66202": {"Johnson County": "Johnson County"},
        "66203": {"Johnson County": "Johnson County"},
        "66204": {"Johnson County": "Johnson County"},
        "66205": {"Johnson County": "Johnson County"},
        "66206": {"Johnson County": "Johnson County"},
        "66207": {"Johnson County": "Johnson County"},
        "66208": {"Johnson County": "Johnson County"},
        "66209": {"Johnson County": "Johnson County"},
        "66210": {"Johnson County": "Johnson County"},
        "66211": {"Johnson County": "Johnson County"},
        "66212": {"Johnson County": "Johnson County"},
        "66213": {"Johnson County": "Johnson County"},
        "66214": {"Johnson County": "Johnson County"},
        "66215": {"Johnson County": "Johnson County"},
        "66216": {"Johnson County": "Johnson County", "Wyandotte County": "Wyandotte County"},
        "66217": {"Johnson County": "Johnson County", "Wyandotte County": "Wyandotte County"},
        "66218": {"Johnson County": "Johnson County"},
        "66219": {"Johnson County": "Johnson County"},
        "66220": {"Johnson County": "Johnson County"},
        "66221": {"Johnson County": "Johnson County"},
        "66223": {"Johnson County": "Johnson County"},
        "66224": {"Johnson County": "Johnson County"},
        "66225": {"Johnson County": "Johnson County"},
        "66226": {"Johnson County": "Johnson County"},
        "66227": {"Johnson County": "Johnson County"},
        "66250": {"Johnson County": "Johnson County"},
        "66251": {"Johnson County": "Johnson County"},
        "66276": {"Johnson County": "Johnson County"},
        "66282": {"Johnson County": "Johnson County"},
        "66283": {"Johnson County": "Johnson County"},
        "66285": {"Johnson County": "Johnson County"},
        "66286": {"Johnson County": "Johnson County"},
        "66401": {"Wabaunsee County": "Wabaunsee County", "Geary County": "Geary County"},
        "66402": {"Shawnee County": "Shawnee County", "Osage County": "Osage County"},
        "66403": {"Marshall County": "Marshall County", "Nemaha County": "Nemaha County"},
        "66404": {"Nemaha County": "Nemaha County", "Marshall County": "Marshall County"},
        "66406": {"Marshall County": "Marshall County"},
        "66407": {"Pottawatomie County": "Pottawatomie County", "Wabaunsee County": "Wabaunsee County"},
        "66408": {"Nemaha County": "Nemaha County"},
        "66409": {
            "Shawnee County": "Shawnee County",
            "Douglas County": "Douglas County",
            "Osage County": "Osage County",
        },
        "66411": {"Marshall County": "Marshall County", "Riley County": "Riley County"},
        "66412": {"Marshall County": "Marshall County", "Washington County": "Washington County"},
        "66413": {"Osage County": "Osage County", "Wabaunsee County": "Wabaunsee County"},
        "66414": {"Osage County": "Osage County", "Shawnee County": "Shawnee County"},
        "66415": {"Nemaha County": "Nemaha County"},
        "66416": {"Jackson County": "Jackson County", "Nemaha County": "Nemaha County"},
        "66417": {"Nemaha County": "Nemaha County"},
        "66418": {"Jackson County": "Jackson County"},
        "66419": {"Jackson County": "Jackson County", "Jefferson County": "Jefferson County"},
        "66420": {"Shawnee County": "Shawnee County"},
        "66422": {"Pottawatomie County": "Pottawatomie County", "Jackson County": "Jackson County"},
        "66423": {"Wabaunsee County": "Wabaunsee County"},
        "66424": {"Brown County": "Brown County", "Atchison County": "Atchison County"},
        "66425": {"Brown County": "Brown County"},
        "66427": {"Marshall County": "Marshall County", "Pottawatomie County": "Pottawatomie County"},
        "66428": {"Nemaha County": "Nemaha County", "Jackson County": "Jackson County"},
        "66429": {"Jefferson County": "Jefferson County"},
        "66431": {"Wabaunsee County": "Wabaunsee County", "Shawnee County": "Shawnee County"},
        "66432": {
            "Pottawatomie County": "Pottawatomie County",
            "Jackson County": "Jackson County",
            "Nemaha County": "Nemaha County",
        },
        "66434": {"Brown County": "Brown County"},
        "66436": {
            "Jackson County": "Jackson County",
            "Atchison County": "Atchison County",
            "Jefferson County": "Jefferson County",
        },
        "66438": {"Marshall County": "Marshall County"},
        "66439": {
            "Brown County": "Brown County",
            "Atchison County": "Atchison County",
            "Jackson County": "Jackson County",
        },
        "66440": {"Jackson County": "Jackson County"},
        "66441": {"Geary County": "Geary County", "Dickinson County": "Dickinson County"},
        "66442": {"Riley County": "Riley County", "Geary County": "Geary County"},
        "66449": {"Riley County": "Riley County"},
        "66451": {"Osage County": "Osage County"},
        "66501": {"Wabaunsee County": "Wabaunsee County"},
        "66502": {
            "Riley County": "Riley County",
            "Pottawatomie County": "Pottawatomie County",
            "Geary County": "Geary County",
            "Wabaunsee County": "Wabaunsee County",
        },
        "66503": {"Riley County": "Riley County"},
        "66505": {"Riley County": "Riley County"},
        "66506": {"Riley County": "Riley County"},
        "66507": {"Wabaunsee County": "Wabaunsee County"},
        "66508": {"Marshall County": "Marshall County"},
        "66509": {"Jackson County": "Jackson County"},
        "66510": {"Osage County": "Osage County"},
        "66512": {
            "Jefferson County": "Jefferson County",
            "Shawnee County": "Shawnee County",
            "Jackson County": "Jackson County",
        },
        "66514": {"Geary County": "Geary County"},
        "66515": {"Brown County": "Brown County"},
        "66516": {"Jackson County": "Jackson County", "Brown County": "Brown County"},
        "66517": {"Riley County": "Riley County"},
        "66518": {"Marshall County": "Marshall County"},
        "66520": {"Pottawatomie County": "Pottawatomie County"},
        "66521": {
            "Pottawatomie County": "Pottawatomie County",
            "Nemaha County": "Nemaha County",
            "Marshall County": "Marshall County",
        },
        "66522": {"Nemaha County": "Nemaha County"},
        "66523": {"Osage County": "Osage County", "Lyon County": "Lyon County"},
        "66524": {
            "Osage County": "Osage County",
            "Douglas County": "Douglas County",
            "Shawnee County": "Shawnee County",
            "Franklin County": "Franklin County",
        },
        "66526": {"Wabaunsee County": "Wabaunsee County"},
        "66527": {"Brown County": "Brown County"},
        "66528": {"Osage County": "Osage County", "Franklin County": "Franklin County"},
        "66531": {"Riley County": "Riley County"},
        "66532": {"Brown County": "Brown County", "Doniphan County": "Doniphan County"},
        "66533": {"Shawnee County": "Shawnee County", "Jackson County": "Jackson County"},
        "66534": {"Nemaha County": "Nemaha County", "Brown County": "Brown County"},
        "66535": {"Pottawatomie County": "Pottawatomie County"},
        "66536": {
            "Pottawatomie County": "Pottawatomie County",
            "Shawnee County": "Shawnee County",
            "Jackson County": "Jackson County",
            "Wabaunsee County": "Wabaunsee County",
        },
        "66537": {"Osage County": "Osage County"},
        "66538": {"Nemaha County": "Nemaha County"},
        "66539": {"Shawnee County": "Shawnee County", "Jackson County": "Jackson County"},
        "66540": {
            "Jackson County": "Jackson County",
            "Nemaha County": "Nemaha County",
            "Pottawatomie County": "Pottawatomie County",
        },
        "66541": {"Marshall County": "Marshall County"},
        "66542": {"Shawnee County": "Shawnee County", "Douglas County": "Douglas County"},
        "66543": {"Osage County": "Osage County"},
        "66544": {"Marshall County": "Marshall County", "Nemaha County": "Nemaha County"},
        "66546": {"Shawnee County": "Shawnee County", "Osage County": "Osage County"},
        "66547": {"Pottawatomie County": "Pottawatomie County", "Wabaunsee County": "Wabaunsee County"},
        "66548": {
            "Marshall County": "Marshall County",
            "Washington County": "Washington County",
            "Riley County": "Riley County",
        },
        "66549": {"Pottawatomie County": "Pottawatomie County", "Marshall County": "Marshall County"},
        "66550": {"Nemaha County": "Nemaha County", "Jackson County": "Jackson County", "Brown County": "Brown County"},
        "66552": {"Jackson County": "Jackson County", "Atchison County": "Atchison County"},
        "66554": {"Riley County": "Riley County"},
        "66601": {"Shawnee County": "Shawnee County"},
        "66603": {"Shawnee County": "Shawnee County"},
        "66604": {"Shawnee County": "Shawnee County"},
        "66605": {"Shawnee County": "Shawnee County"},
        "66606": {"Shawnee County": "Shawnee County"},
        "66607": {"Shawnee County": "Shawnee County"},
        "66608": {"Shawnee County": "Shawnee County"},
        "66609": {"Shawnee County": "Shawnee County"},
        "66610": {"Shawnee County": "Shawnee County", "Wabaunsee County": "Wabaunsee County"},
        "66611": {"Shawnee County": "Shawnee County"},
        "66612": {"Shawnee County": "Shawnee County"},
        "66614": {"Shawnee County": "Shawnee County", "Wabaunsee County": "Wabaunsee County"},
        "66615": {"Shawnee County": "Shawnee County", "Wabaunsee County": "Wabaunsee County"},
        "66616": {"Shawnee County": "Shawnee County"},
        "66617": {
            "Shawnee County": "Shawnee County",
            "Jefferson County": "Jefferson County",
            "Jackson County": "Jackson County",
        },
        "66618": {"Shawnee County": "Shawnee County", "Jackson County": "Jackson County"},
        "66619": {"Shawnee County": "Shawnee County"},
        "66620": {"Shawnee County": "Shawnee County"},
        "66621": {"Shawnee County": "Shawnee County"},
        "66622": {"Shawnee County": "Shawnee County"},
        "66624": {"Shawnee County": "Shawnee County"},
        "66625": {"Shawnee County": "Shawnee County"},
        "66626": {"Shawnee County": "Shawnee County"},
        "66629": {"Shawnee County": "Shawnee County"},
        "66630": {"Shawnee County": "Shawnee County"},
        "66636": {"Shawnee County": "Shawnee County"},
        "66647": {"Shawnee County": "Shawnee County"},
        "66667": {"Shawnee County": "Shawnee County"},
        "66675": {"Shawnee County": "Shawnee County"},
        "66683": {"Shawnee County": "Shawnee County"},
        "66699": {"Shawnee County": "Shawnee County"},
        "66701": {"Bourbon County": "Bourbon County", "Crawford County": "Crawford County"},
        "66710": {"Wilson County": "Wilson County"},
        "66711": {"Crawford County": "Crawford County", "Bourbon County": "Bourbon County"},
        "66712": {"Crawford County": "Crawford County"},
        "66713": {"Cherokee County": "Cherokee County"},
        "66714": {"Wilson County": "Wilson County"},
        "66716": {"Bourbon County": "Bourbon County", "Allen County": "Allen County"},
        "66717": {"Wilson County": "Wilson County", "Woodson County": "Woodson County"},
        "66720": {
            "Neosho County": "Neosho County",
            "Wilson County": "Wilson County",
            "Allen County": "Allen County",
            "Woodson County": "Woodson County",
        },
        "66724": {"Crawford County": "Crawford County", "Cherokee County": "Cherokee County"},
        "66725": {"Cherokee County": "Cherokee County"},
        "66728": {"Cherokee County": "Cherokee County"},
        "66732": {"Allen County": "Allen County"},
        "66733": {"Neosho County": "Neosho County"},
        "66734": {"Crawford County": "Crawford County"},
        "66735": {"Crawford County": "Crawford County"},
        "66736": {
            "Wilson County": "Wilson County",
            "Elk County": "Elk County",
            "Montgomery County": "Montgomery County",
            "Woodson County": "Woodson County",
            "Greenwood County": "Greenwood County",
        },
        "66738": {"Bourbon County": "Bourbon County", "Linn County": "Linn County"},
        "66739": {"Cherokee County": "Cherokee County"},
        "66740": {"Neosho County": "Neosho County"},
        "66741": {"Bourbon County": "Bourbon County"},
        "66742": {"Allen County": "Allen County"},
        "66743": {"Crawford County": "Crawford County"},
        "66746": {"Crawford County": "Crawford County", "Bourbon County": "Bourbon County"},
        "66748": {"Allen County": "Allen County", "Neosho County": "Neosho County", "Woodson County": "Woodson County"},
        "66749": {"Allen County": "Allen County", "Woodson County": "Woodson County"},
        "66751": {"Allen County": "Allen County"},
        "66753": {
            "Crawford County": "Crawford County",
            "Cherokee County": "Cherokee County",
            "Labette County": "Labette County",
            "Neosho County": "Neosho County",
        },
        "66754": {"Bourbon County": "Bourbon County", "Linn County": "Linn County"},
        "66755": {"Allen County": "Allen County", "Bourbon County": "Bourbon County"},
        "66756": {"Crawford County": "Crawford County"},
        "66757": {"Wilson County": "Wilson County", "Montgomery County": "Montgomery County"},
        "66758": {
            "Woodson County": "Woodson County",
            "Anderson County": "Anderson County",
            "Coffey County": "Coffey County",
            "Allen County": "Allen County",
        },
        "66760": {"Crawford County": "Crawford County"},
        "66761": {"Woodson County": "Woodson County", "Allen County": "Allen County"},
        "66762": {"Crawford County": "Crawford County", "Cherokee County": "Cherokee County"},
        "66763": {"Crawford County": "Crawford County"},
        "66767": {"Linn County": "Linn County"},
        "66769": {"Bourbon County": "Bourbon County"},
        "66770": {"Cherokee County": "Cherokee County"},
        "66771": {"Neosho County": "Neosho County"},
        "66772": {"Allen County": "Allen County", "Neosho County": "Neosho County", "Bourbon County": "Bourbon County"},
        "66773": {"Cherokee County": "Cherokee County"},
        "66775": {"Neosho County": "Neosho County", "Bourbon County": "Bourbon County"},
        "66776": {
            "Neosho County": "Neosho County",
            "Wilson County": "Wilson County",
            "Labette County": "Labette County",
        },
        "66777": {
            "Woodson County": "Woodson County",
            "Greenwood County": "Greenwood County",
            "Wilson County": "Wilson County",
        },
        "66778": {"Cherokee County": "Cherokee County"},
        "66779": {"Bourbon County": "Bourbon County"},
        "66780": {
            "Crawford County": "Crawford County",
            "Neosho County": "Neosho County",
            "Bourbon County": "Bourbon County",
        },
        "66781": {"Cherokee County": "Cherokee County", "Crawford County": "Crawford County"},
        "66782": {"Cherokee County": "Cherokee County"},
        "66783": {"Woodson County": "Woodson County", "Coffey County": "Coffey County"},
        "66801": {"Lyon County": "Lyon County", "Chase County": "Chase County"},
        "66830": {"Lyon County": "Lyon County"},
        "66833": {"Lyon County": "Lyon County"},
        "66834": {
            "Wabaunsee County": "Wabaunsee County",
            "Geary County": "Geary County",
            "Morris County": "Morris County",
        },
        "66835": {"Lyon County": "Lyon County"},
        "66838": {"Morris County": "Morris County", "Chase County": "Chase County", "Marion County": "Marion County"},
        "66839": {"Coffey County": "Coffey County"},
        "66840": {"Marion County": "Marion County", "Butler County": "Butler County", "Chase County": "Chase County"},
        "66842": {"Butler County": "Butler County"},
        "66843": {"Chase County": "Chase County", "Marion County": "Marion County"},
        "66845": {"Chase County": "Chase County"},
        "66846": {
            "Morris County": "Morris County",
            "Lyon County": "Lyon County",
            "Chase County": "Chase County",
            "Wabaunsee County": "Wabaunsee County",
        },
        "66849": {"Morris County": "Morris County", "Geary County": "Geary County"},
        "66850": {"Chase County": "Chase County"},
        "66851": {"Marion County": "Marion County"},
        "66852": {
            "Coffey County": "Coffey County",
            "Greenwood County": "Greenwood County",
            "Woodson County": "Woodson County",
        },
        "66853": {"Greenwood County": "Greenwood County"},
        "66854": {"Lyon County": "Lyon County", "Coffey County": "Coffey County"},
        "66855": {"Greenwood County": "Greenwood County"},
        "66856": {"Coffey County": "Coffey County", "Osage County": "Osage County"},
        "66857": {"Coffey County": "Coffey County"},
        "66858": {"Marion County": "Marion County", "Chase County": "Chase County"},
        "66859": {"Marion County": "Marion County", "Morris County": "Morris County"},
        "66860": {"Greenwood County": "Greenwood County", "Lyon County": "Lyon County"},
        "66861": {"Marion County": "Marion County"},
        "66862": {"Chase County": "Chase County"},
        "66863": {"Greenwood County": "Greenwood County"},
        "66864": {"Lyon County": "Lyon County", "Coffey County": "Coffey County"},
        "66865": {"Lyon County": "Lyon County", "Chase County": "Chase County"},
        "66866": {"Marion County": "Marion County", "Harvey County": "Harvey County"},
        "66868": {"Lyon County": "Lyon County", "Osage County": "Osage County", "Coffey County": "Coffey County"},
        "66869": {"Chase County": "Chase County", "Marion County": "Marion County"},
        "66870": {"Greenwood County": "Greenwood County", "Woodson County": "Woodson County"},
        "66871": {"Coffey County": "Coffey County", "Osage County": "Osage County"},
        "66872": {"Morris County": "Morris County", "Geary County": "Geary County"},
        "66873": {"Morris County": "Morris County"},
        "66901": {"Cloud County": "Cloud County", "Republic County": "Republic County"},
        "66930": {"Republic County": "Republic County", "Cloud County": "Cloud County"},
        "66932": {"Smith County": "Smith County"},
        "66933": {"Washington County": "Washington County", "Riley County": "Riley County"},
        "66935": {"Republic County": "Republic County", "Cloud County": "Cloud County"},
        "66936": {"Jewell County": "Jewell County"},
        "66937": {"Washington County": "Washington County", "Clay County": "Clay County"},
        "66938": {
            "Cloud County": "Cloud County",
            "Washington County": "Washington County",
            "Clay County": "Clay County",
            "Republic County": "Republic County",
        },
        "66939": {"Republic County": "Republic County", "Jewell County": "Jewell County"},
        "66940": {"Republic County": "Republic County", "Cloud County": "Cloud County"},
        "66941": {"Jewell County": "Jewell County", "Smith County": "Smith County"},
        "66942": {"Jewell County": "Jewell County"},
        "66943": {"Washington County": "Washington County"},
        "66944": {"Washington County": "Washington County"},
        "66945": {"Washington County": "Washington County", "Marshall County": "Marshall County"},
        "66946": {"Washington County": "Washington County"},
        "66948": {
            "Cloud County": "Cloud County",
            "Republic County": "Republic County",
            "Jewell County": "Jewell County",
        },
        "66949": {"Jewell County": "Jewell County", "Republic County": "Republic County"},
        "66951": {"Smith County": "Smith County", "Phillips County": "Phillips County"},
        "66952": {"Smith County": "Smith County", "Jewell County": "Jewell County"},
        "66953": {"Washington County": "Washington County"},
        "66955": {"Washington County": "Washington County"},
        "66956": {"Jewell County": "Jewell County", "Mitchell County": "Mitchell County"},
        "66958": {"Washington County": "Washington County"},
        "66959": {"Republic County": "Republic County"},
        "66960": {"Republic County": "Republic County", "Washington County": "Washington County"},
        "66961": {"Republic County": "Republic County"},
        "66962": {"Washington County": "Washington County", "Clay County": "Clay County"},
        "66963": {"Jewell County": "Jewell County"},
        "66964": {"Republic County": "Republic County"},
        "66966": {"Republic County": "Republic County", "Cloud County": "Cloud County"},
        "66967": {"Smith County": "Smith County"},
        "66968": {"Washington County": "Washington County"},
        "66970": {"Jewell County": "Jewell County"},
        "67001": {"Sedgwick County": "Sedgwick County"},
        "67002": {"Butler County": "Butler County"},
        "67003": {"Harper County": "Harper County"},
        "67004": {
            "Sumner County": "Sumner County",
            "Harper County": "Harper County",
            "Kingman County": "Kingman County",
        },
        "67005": {"Cowley County": "Cowley County"},
        "67008": {"Cowley County": "Cowley County", "Butler County": "Butler County"},
        "67009": {"Harper County": "Harper County", "Barber County": "Barber County"},
        "67010": {"Butler County": "Butler County"},
        "67012": {"Butler County": "Butler County"},
        "67013": {"Sumner County": "Sumner County"},
        "67016": {"Sedgwick County": "Sedgwick County"},
        "67017": {"Butler County": "Butler County", "Sedgwick County": "Sedgwick County"},
        "67018": {"Harper County": "Harper County", "Sumner County": "Sumner County"},
        "67019": {"Cowley County": "Cowley County"},
        "67020": {"Harvey County": "Harvey County", "Reno County": "Reno County", "Sedgwick County": "Sedgwick County"},
        "67021": {"Pratt County": "Pratt County"},
        "67022": {"Sumner County": "Sumner County"},
        "67023": {"Cowley County": "Cowley County"},
        "67024": {"Chautauqua County": "Chautauqua County", "Cowley County": "Cowley County"},
        "67025": {
            "Sedgwick County": "Sedgwick County",
            "Kingman County": "Kingman County",
            "Reno County": "Reno County",
        },
        "67026": {"Sedgwick County": "Sedgwick County", "Sumner County": "Sumner County"},
        "67028": {"Pratt County": "Pratt County", "Barber County": "Barber County", "Kiowa County": "Kiowa County"},
        "67029": {"Comanche County": "Comanche County"},
        "67030": {"Sedgwick County": "Sedgwick County"},
        "67031": {"Sumner County": "Sumner County", "Sedgwick County": "Sedgwick County"},
        "67035": {"Kingman County": "Kingman County", "Pratt County": "Pratt County", "Reno County": "Reno County"},
        "67036": {"Harper County": "Harper County"},
        "67037": {"Sedgwick County": "Sedgwick County"},
        "67038": {"Cowley County": "Cowley County"},
        "67039": {
            "Butler County": "Butler County",
            "Cowley County": "Cowley County",
            "Sedgwick County": "Sedgwick County",
        },
        "67041": {"Butler County": "Butler County"},
        "67042": {"Butler County": "Butler County"},
        "67045": {"Greenwood County": "Greenwood County", "Butler County": "Butler County"},
        "67047": {"Greenwood County": "Greenwood County", "Wilson County": "Wilson County", "Elk County": "Elk County"},
        "67049": {"Harper County": "Harper County", "Sumner County": "Sumner County"},
        "67050": {"Sedgwick County": "Sedgwick County"},
        "67051": {"Sumner County": "Sumner County", "Cowley County": "Cowley County"},
        "67052": {"Sedgwick County": "Sedgwick County"},
        "67053": {"Marion County": "Marion County"},
        "67054": {"Kiowa County": "Kiowa County", "Edwards County": "Edwards County"},
        "67055": {"Sedgwick County": "Sedgwick County"},
        "67056": {"Harvey County": "Harvey County"},
        "67057": {"Barber County": "Barber County"},
        "67058": {"Harper County": "Harper County", "Kingman County": "Kingman County"},
        "67059": {"Kiowa County": "Kiowa County", "Edwards County": "Edwards County", "Pratt County": "Pratt County"},
        "67060": {"Sedgwick County": "Sedgwick County"},
        "67061": {"Barber County": "Barber County", "Harper County": "Harper County"},
        "67062": {
            "Harvey County": "Harvey County",
            "McPherson County": "McPherson County",
            "Marion County": "Marion County",
        },
        "67063": {"Marion County": "Marion County"},
        "67065": {"Barber County": "Barber County", "Pratt County": "Pratt County"},
        "67066": {"Pratt County": "Pratt County"},
        "67067": {"Sedgwick County": "Sedgwick County"},
        "67068": {"Kingman County": "Kingman County", "Reno County": "Reno County"},
        "67070": {"Barber County": "Barber County"},
        "67071": {"Barber County": "Barber County"},
        "67072": {"Butler County": "Butler County", "Cowley County": "Cowley County"},
        "67073": {"Marion County": "Marion County"},
        "67074": {"Butler County": "Butler County"},
        "67101": {"Sedgwick County": "Sedgwick County"},
        "67102": {"Cowley County": "Cowley County"},
        "67103": {"Sumner County": "Sumner County"},
        "67104": {"Barber County": "Barber County"},
        "67105": {"Sumner County": "Sumner County"},
        "67106": {
            "Sumner County": "Sumner County",
            "Sedgwick County": "Sedgwick County",
            "Kingman County": "Kingman County",
        },
        "67107": {"McPherson County": "McPherson County", "Harvey County": "Harvey County"},
        "67108": {"Sedgwick County": "Sedgwick County", "Reno County": "Reno County"},
        "67109": {"Kiowa County": "Kiowa County"},
        "67110": {
            "Sedgwick County": "Sedgwick County",
            "Sumner County": "Sumner County",
            "Cowley County": "Cowley County",
        },
        "67111": {"Kingman County": "Kingman County"},
        "67112": {"Kingman County": "Kingman County", "Barber County": "Barber County"},
        "67114": {
            "Harvey County": "Harvey County",
            "Marion County": "Marion County",
            "Butler County": "Butler County",
            "McPherson County": "McPherson County",
        },
        "67117": {"Harvey County": "Harvey County"},
        "67118": {
            "Kingman County": "Kingman County",
            "Sedgwick County": "Sedgwick County",
            "Sumner County": "Sumner County",
        },
        "67119": {"Sumner County": "Sumner County", "Cowley County": "Cowley County"},
        "67120": {"Sumner County": "Sumner County", "Sedgwick County": "Sedgwick County"},
        "67122": {"Greenwood County": "Greenwood County", "Elk County": "Elk County"},
        "67123": {"Butler County": "Butler County"},
        "67124": {"Pratt County": "Pratt County"},
        "67127": {"Comanche County": "Comanche County", "Clark County": "Clark County"},
        "67131": {"Cowley County": "Cowley County", "Butler County": "Butler County"},
        "67132": {"Butler County": "Butler County"},
        "67133": {"Butler County": "Butler County", "Sedgwick County": "Sedgwick County"},
        "67134": {"Pratt County": "Pratt County", "Barber County": "Barber County"},
        "67135": {"Harvey County": "Harvey County", "Sedgwick County": "Sedgwick County"},
        "67137": {"Greenwood County": "Greenwood County", "Elk County": "Elk County"},
        "67138": {"Barber County": "Barber County", "Harper County": "Harper County"},
        "67140": {"Sumner County": "Sumner County"},
        "67142": {"Kingman County": "Kingman County"},
        "67143": {"Barber County": "Barber County"},
        "67144": {"Butler County": "Butler County"},
        "67146": {"Cowley County": "Cowley County", "Sumner County": "Sumner County"},
        "67147": {"Sedgwick County": "Sedgwick County", "Harvey County": "Harvey County"},
        "67149": {"Sedgwick County": "Sedgwick County"},
        "67150": {"Harper County": "Harper County"},
        "67151": {"Harvey County": "Harvey County", "Marion County": "Marion County"},
        "67152": {"Sumner County": "Sumner County"},
        "67154": {"Butler County": "Butler County", "Harvey County": "Harvey County"},
        "67155": {"Comanche County": "Comanche County", "Kiowa County": "Kiowa County"},
        "67156": {"Cowley County": "Cowley County"},
        "67159": {"Kingman County": "Kingman County", "Harper County": "Harper County"},
        "67201": {"Sedgwick County": "Sedgwick County"},
        "67202": {"Sedgwick County": "Sedgwick County"},
        "67203": {"Sedgwick County": "Sedgwick County"},
        "67204": {"Sedgwick County": "Sedgwick County"},
        "67205": {"Sedgwick County": "Sedgwick County"},
        "67206": {"Sedgwick County": "Sedgwick County"},
        "67207": {"Sedgwick County": "Sedgwick County"},
        "67208": {"Sedgwick County": "Sedgwick County"},
        "67209": {"Sedgwick County": "Sedgwick County"},
        "67210": {"Sedgwick County": "Sedgwick County"},
        "67211": {"Sedgwick County": "Sedgwick County"},
        "67212": {"Sedgwick County": "Sedgwick County"},
        "67213": {"Sedgwick County": "Sedgwick County"},
        "67214": {"Sedgwick County": "Sedgwick County"},
        "67215": {"Sedgwick County": "Sedgwick County"},
        "67216": {"Sedgwick County": "Sedgwick County"},
        "67217": {"Sedgwick County": "Sedgwick County"},
        "67218": {"Sedgwick County": "Sedgwick County"},
        "67219": {"Sedgwick County": "Sedgwick County"},
        "67220": {"Sedgwick County": "Sedgwick County"},
        "67221": {"Sedgwick County": "Sedgwick County"},
        "67223": {"Sedgwick County": "Sedgwick County"},
        "67226": {"Sedgwick County": "Sedgwick County"},
        "67227": {"Sedgwick County": "Sedgwick County"},
        "67228": {"Sedgwick County": "Sedgwick County", "Butler County": "Butler County"},
        "67230": {"Sedgwick County": "Sedgwick County", "Butler County": "Butler County"},
        "67232": {"Sedgwick County": "Sedgwick County", "Butler County": "Butler County"},
        "67235": {"Sedgwick County": "Sedgwick County"},
        "67260": {"Sedgwick County": "Sedgwick County"},
        "67275": {"Sedgwick County": "Sedgwick County"},
        "67276": {"Sedgwick County": "Sedgwick County"},
        "67277": {"Sedgwick County": "Sedgwick County"},
        "67278": {"Sedgwick County": "Sedgwick County"},
        "67301": {"Montgomery County": "Montgomery County"},
        "67330": {"Labette County": "Labette County"},
        "67332": {"Labette County": "Labette County"},
        "67333": {"Montgomery County": "Montgomery County"},
        "67334": {"Chautauqua County": "Chautauqua County"},
        "67335": {
            "Montgomery County": "Montgomery County",
            "Labette County": "Labette County",
            "Wilson County": "Wilson County",
        },
        "67336": {"Labette County": "Labette County", "Cherokee County": "Cherokee County"},
        "67337": {"Montgomery County": "Montgomery County", "Labette County": "Labette County"},
        "67340": {"Montgomery County": "Montgomery County"},
        "67341": {"Labette County": "Labette County", "Neosho County": "Neosho County"},
        "67342": {"Labette County": "Labette County"},
        "67344": {
            "Montgomery County": "Montgomery County",
            "Chautauqua County": "Chautauqua County",
            "Elk County": "Elk County",
            "Wilson County": "Wilson County",
        },
        "67345": {"Elk County": "Elk County"},
        "67346": {"Elk County": "Elk County", "Chautauqua County": "Chautauqua County"},
        "67347": {"Montgomery County": "Montgomery County", "Chautauqua County": "Chautauqua County"},
        "67349": {"Elk County": "Elk County", "Chautauqua County": "Chautauqua County"},
        "67351": {"Labette County": "Labette County", "Montgomery County": "Montgomery County"},
        "67352": {"Elk County": "Elk County", "Chautauqua County": "Chautauqua County"},
        "67353": {"Elk County": "Elk County", "Chautauqua County": "Chautauqua County"},
        "67354": {"Labette County": "Labette County"},
        "67355": {"Chautauqua County": "Chautauqua County", "Montgomery County": "Montgomery County"},
        "67356": {"Labette County": "Labette County", "Cherokee County": "Cherokee County"},
        "67357": {"Labette County": "Labette County", "Neosho County": "Neosho County"},
        "67360": {"Chautauqua County": "Chautauqua County"},
        "67361": {"Chautauqua County": "Chautauqua County"},
        "67363": {"Montgomery County": "Montgomery County"},
        "67364": {"Montgomery County": "Montgomery County"},
        "67401": {"Saline County": "Saline County", "Ottawa County": "Ottawa County"},
        "67402": {"Saline County": "Saline County"},
        "67410": {"Dickinson County": "Dickinson County", "Clay County": "Clay County"},
        "67416": {"Saline County": "Saline County", "McPherson County": "McPherson County"},
        "67417": {"Cloud County": "Cloud County"},
        "67418": {
            "Lincoln County": "Lincoln County",
            "Mitchell County": "Mitchell County",
            "Ottawa County": "Ottawa County",
        },
        "67420": {
            "Mitchell County": "Mitchell County",
            "Cloud County": "Cloud County",
            "Jewell County": "Jewell County",
        },
        "67422": {"Ottawa County": "Ottawa County"},
        "67423": {"Lincoln County": "Lincoln County", "Ellsworth County": "Ellsworth County"},
        "67425": {"Saline County": "Saline County", "Ellsworth County": "Ellsworth County"},
        "67427": {
            "Rice County": "Rice County",
            "Ellsworth County": "Ellsworth County",
            "Barton County": "Barton County",
        },
        "67428": {"McPherson County": "McPherson County", "Marion County": "Marion County"},
        "67430": {
            "Mitchell County": "Mitchell County",
            "Osborne County": "Osborne County",
            "Jewell County": "Jewell County",
        },
        "67431": {"Dickinson County": "Dickinson County"},
        "67432": {"Clay County": "Clay County", "Ottawa County": "Ottawa County", "Riley County": "Riley County"},
        "67436": {"Ottawa County": "Ottawa County", "Cloud County": "Cloud County"},
        "67437": {"Osborne County": "Osborne County", "Smith County": "Smith County"},
        "67438": {"Marion County": "Marion County"},
        "67439": {"Ellsworth County": "Ellsworth County", "Lincoln County": "Lincoln County"},
        "67441": {"Dickinson County": "Dickinson County"},
        "67442": {"Saline County": "Saline County"},
        "67443": {"McPherson County": "McPherson County"},
        "67444": {"Rice County": "Rice County", "Ellsworth County": "Ellsworth County"},
        "67445": {"Cloud County": "Cloud County", "Ottawa County": "Ottawa County"},
        "67446": {"Mitchell County": "Mitchell County"},
        "67447": {"Clay County": "Clay County", "Riley County": "Riley County"},
        "67448": {
            "Saline County": "Saline County",
            "Dickinson County": "Dickinson County",
            "McPherson County": "McPherson County",
        },
        "67449": {
            "Dickinson County": "Dickinson County",
            "Morris County": "Morris County",
            "Marion County": "Marion County",
        },
        "67450": {"Ellsworth County": "Ellsworth County", "Barton County": "Barton County"},
        "67451": {"Dickinson County": "Dickinson County", "Marion County": "Marion County"},
        "67452": {"Mitchell County": "Mitchell County", "Lincoln County": "Lincoln County"},
        "67454": {"Ellsworth County": "Ellsworth County"},
        "67455": {"Lincoln County": "Lincoln County", "Ottawa County": "Ottawa County", "Cloud County": "Cloud County"},
        "67456": {"McPherson County": "McPherson County", "Saline County": "Saline County"},
        "67457": {"Rice County": "Rice County"},
        "67458": {
            "Clay County": "Clay County",
            "Ottawa County": "Ottawa County",
            "Dickinson County": "Dickinson County",
        },
        "67459": {"Ellsworth County": "Ellsworth County", "Rice County": "Rice County"},
        "67460": {"McPherson County": "McPherson County"},
        "67464": {
            "McPherson County": "McPherson County",
            "Ellsworth County": "Ellsworth County",
            "Saline County": "Saline County",
        },
        "67466": {"Cloud County": "Cloud County", "Ottawa County": "Ottawa County", "Clay County": "Clay County"},
        "67467": {"Ottawa County": "Ottawa County", "Lincoln County": "Lincoln County"},
        "67468": {"Clay County": "Clay County"},
        "67470": {"Saline County": "Saline County", "Ottawa County": "Ottawa County"},
        "67473": {"Osborne County": "Osborne County"},
        "67474": {"Osborne County": "Osborne County", "Smith County": "Smith County"},
        "67475": {"Marion County": "Marion County", "Dickinson County": "Dickinson County"},
        "67476": {"McPherson County": "McPherson County"},
        "67478": {"Mitchell County": "Mitchell County"},
        "67480": {
            "Dickinson County": "Dickinson County",
            "Ottawa County": "Ottawa County",
            "Saline County": "Saline County",
        },
        "67481": {"Lincoln County": "Lincoln County", "Russell County": "Russell County"},
        "67482": {"Dickinson County": "Dickinson County"},
        "67483": {"Marion County": "Marion County"},
        "67484": {
            "Ottawa County": "Ottawa County",
            "Saline County": "Saline County",
            "Lincoln County": "Lincoln County",
        },
        "67485": {"Mitchell County": "Mitchell County", "Osborne County": "Osborne County"},
        "67487": {"Clay County": "Clay County", "Dickinson County": "Dickinson County", "Geary County": "Geary County"},
        "67490": {
            "Ellsworth County": "Ellsworth County",
            "Russell County": "Russell County",
            "Lincoln County": "Lincoln County",
        },
        "67491": {"McPherson County": "McPherson County", "Rice County": "Rice County"},
        "67492": {"Dickinson County": "Dickinson County"},
        "67501": {"Reno County": "Reno County"},
        "67502": {"Reno County": "Reno County", "Rice County": "Rice County"},
        "67505": {"Reno County": "Reno County"},
        "67510": {"Reno County": "Reno County"},
        "67511": {"Barton County": "Barton County", "Rush County": "Rush County"},
        "67512": {"Rice County": "Rice County", "Reno County": "Reno County"},
        "67513": {"Rush County": "Rush County"},
        "67514": {"Reno County": "Reno County"},
        "67515": {"Ness County": "Ness County"},
        "67516": {"Ness County": "Ness County"},
        "67518": {"Ness County": "Ness County", "Lane County": "Lane County"},
        "67519": {"Edwards County": "Edwards County", "Pawnee County": "Pawnee County"},
        "67520": {"Rush County": "Rush County", "Ellis County": "Ellis County"},
        "67521": {"Ness County": "Ness County", "Trego County": "Trego County", "Rush County": "Rush County"},
        "67522": {"Reno County": "Reno County", "Harvey County": "Harvey County"},
        "67523": {"Pawnee County": "Pawnee County", "Hodgeman County": "Hodgeman County"},
        "67524": {"Rice County": "Rice County"},
        "67525": {"Barton County": "Barton County"},
        "67526": {"Barton County": "Barton County", "Stafford County": "Stafford County", "Rice County": "Rice County"},
        "67529": {"Pawnee County": "Pawnee County"},
        "67530": {"Barton County": "Barton County", "Stafford County": "Stafford County"},
        "67543": {"Reno County": "Reno County", "Sedgwick County": "Sedgwick County"},
        "67544": {"Barton County": "Barton County", "Russell County": "Russell County"},
        "67545": {"Stafford County": "Stafford County"},
        "67546": {
            "McPherson County": "McPherson County",
            "Rice County": "Rice County",
            "Reno County": "Reno County",
            "Harvey County": "Harvey County",
        },
        "67547": {
            "Edwards County": "Edwards County",
            "Hodgeman County": "Hodgeman County",
            "Pawnee County": "Pawnee County",
        },
        "67548": {"Rush County": "Rush County"},
        "67550": {"Pawnee County": "Pawnee County", "Stafford County": "Stafford County"},
        "67552": {"Edwards County": "Edwards County"},
        "67553": {"Rush County": "Rush County"},
        "67554": {"Rice County": "Rice County"},
        "67556": {"Rush County": "Rush County", "Ellis County": "Ellis County"},
        "67557": {
            "Stafford County": "Stafford County",
            "Pratt County": "Pratt County",
            "Pawnee County": "Pawnee County",
            "Edwards County": "Edwards County",
        },
        "67559": {"Rush County": "Rush County"},
        "67560": {"Ness County": "Ness County"},
        "67561": {"Reno County": "Reno County", "Rice County": "Rice County"},
        "67563": {
            "Edwards County": "Edwards County",
            "Ford County": "Ford County",
            "Hodgeman County": "Hodgeman County",
        },
        "67564": {"Barton County": "Barton County"},
        "67565": {"Rush County": "Rush County", "Barton County": "Barton County"},
        "67566": {"Reno County": "Reno County"},
        "67567": {
            "Barton County": "Barton County",
            "Pawnee County": "Pawnee County",
            "Rush County": "Rush County",
            "Stafford County": "Stafford County",
        },
        "67568": {"Reno County": "Reno County"},
        "67570": {"Reno County": "Reno County", "Kingman County": "Kingman County"},
        "67572": {"Ness County": "Ness County", "Trego County": "Trego County"},
        "67573": {"Rice County": "Rice County"},
        "67574": {"Pawnee County": "Pawnee County"},
        "67575": {"Rush County": "Rush County", "Pawnee County": "Pawnee County"},
        "67576": {"Stafford County": "Stafford County", "Pratt County": "Pratt County"},
        "67578": {"Stafford County": "Stafford County", "Reno County": "Reno County"},
        "67579": {"Rice County": "Rice County", "Reno County": "Reno County"},
        "67581": {"Reno County": "Reno County"},
        "67583": {"Reno County": "Reno County", "Pratt County": "Pratt County", "Stafford County": "Stafford County"},
        "67584": {"Ness County": "Ness County", "Trego County": "Trego County", "Gove County": "Gove County"},
        "67585": {"Reno County": "Reno County"},
        "67601": {"Ellis County": "Ellis County"},
        "67621": {"Phillips County": "Phillips County"},
        "67622": {"Norton County": "Norton County"},
        "67623": {"Osborne County": "Osborne County"},
        "67625": {"Graham County": "Graham County"},
        "67626": {"Russell County": "Russell County"},
        "67627": {"Ellis County": "Ellis County"},
        "67628": {"Smith County": "Smith County"},
        "67629": {"Norton County": "Norton County", "Decatur County": "Decatur County"},
        "67631": {"Trego County": "Trego County", "Graham County": "Graham County"},
        "67632": {"Rooks County": "Rooks County", "Graham County": "Graham County"},
        "67634": {"Russell County": "Russell County"},
        "67635": {"Decatur County": "Decatur County"},
        "67637": {"Ellis County": "Ellis County", "Trego County": "Trego County"},
        "67638": {"Smith County": "Smith County"},
        "67639": {"Phillips County": "Phillips County", "Rooks County": "Rooks County"},
        "67640": {"Russell County": "Russell County", "Ellis County": "Ellis County"},
        "67642": {"Graham County": "Graham County", "Rooks County": "Rooks County"},
        "67643": {"Decatur County": "Decatur County"},
        "67644": {"Phillips County": "Phillips County", "Smith County": "Smith County"},
        "67645": {"Norton County": "Norton County", "Graham County": "Graham County"},
        "67646": {
            "Phillips County": "Phillips County",
            "Rooks County": "Rooks County",
            "Norton County": "Norton County",
        },
        "67647": {"Phillips County": "Phillips County"},
        "67648": {
            "Russell County": "Russell County",
            "Osborne County": "Osborne County",
            "Lincoln County": "Lincoln County",
        },
        "67649": {"Russell County": "Russell County", "Osborne County": "Osborne County"},
        "67650": {"Graham County": "Graham County"},
        "67651": {
            "Osborne County": "Osborne County",
            "Rooks County": "Rooks County",
            "Ellis County": "Ellis County",
            "Russell County": "Russell County",
        },
        "67653": {"Decatur County": "Decatur County", "Norton County": "Norton County"},
        "67654": {"Norton County": "Norton County"},
        "67656": {"Trego County": "Trego County", "Graham County": "Graham County"},
        "67657": {"Rooks County": "Rooks County", "Graham County": "Graham County"},
        "67658": {"Russell County": "Russell County", "Osborne County": "Osborne County"},
        "67659": {"Graham County": "Graham County", "Ellis County": "Ellis County", "Rooks County": "Rooks County"},
        "67660": {"Ellis County": "Ellis County"},
        "67661": {"Phillips County": "Phillips County", "Rooks County": "Rooks County"},
        "67663": {"Rooks County": "Rooks County", "Ellis County": "Ellis County"},
        "67664": {"Phillips County": "Phillips County"},
        "67665": {"Russell County": "Russell County", "Barton County": "Barton County"},
        "67667": {"Ellis County": "Ellis County"},
        "67669": {"Rooks County": "Rooks County"},
        "67671": {"Ellis County": "Ellis County"},
        "67672": {"Trego County": "Trego County", "Graham County": "Graham County"},
        "67673": {"Russell County": "Russell County", "Osborne County": "Osborne County"},
        "67674": {"Ellis County": "Ellis County"},
        "67675": {"Rooks County": "Rooks County", "Osborne County": "Osborne County"},
        "67701": {"Thomas County": "Thomas County", "Rawlins County": "Rawlins County"},
        "67730": {"Rawlins County": "Rawlins County"},
        "67731": {"Cheyenne County": "Cheyenne County"},
        "67732": {"Thomas County": "Thomas County", "Sherman County": "Sherman County", "Logan County": "Logan County"},
        "67733": {"Sherman County": "Sherman County"},
        "67734": {"Thomas County": "Thomas County"},
        "67735": {"Sherman County": "Sherman County"},
        "67736": {"Gove County": "Gove County"},
        "67737": {"Gove County": "Gove County"},
        "67738": {"Gove County": "Gove County", "Sheridan County": "Sheridan County"},
        "67739": {"Rawlins County": "Rawlins County", "Decatur County": "Decatur County"},
        "67740": {"Sheridan County": "Sheridan County", "Graham County": "Graham County"},
        "67741": {"Sherman County": "Sherman County", "Cheyenne County": "Cheyenne County"},
        "67743": {"Thomas County": "Thomas County"},
        "67744": {"Rawlins County": "Rawlins County"},
        "67745": {"Rawlins County": "Rawlins County", "Cheyenne County": "Cheyenne County"},
        "67747": {"Logan County": "Logan County", "Thomas County": "Thomas County"},
        "67748": {
            "Logan County": "Logan County",
            "Thomas County": "Thomas County",
            "Gove County": "Gove County",
            "Sheridan County": "Sheridan County",
        },
        "67749": {"Decatur County": "Decatur County", "Rawlins County": "Rawlins County"},
        "67751": {"Gove County": "Gove County", "Sheridan County": "Sheridan County"},
        "67752": {"Gove County": "Gove County", "Trego County": "Trego County", "Sheridan County": "Sheridan County"},
        "67753": {"Thomas County": "Thomas County", "Sheridan County": "Sheridan County"},
        "67756": {"Cheyenne County": "Cheyenne County", "Sherman County": "Sherman County"},
        "67757": {
            "Sheridan County": "Sheridan County",
            "Decatur County": "Decatur County",
            "Thomas County": "Thomas County",
        },
        "67758": {"Wallace County": "Wallace County", "Wichita County": "Wichita County"},
        "67761": {"Wallace County": "Wallace County", "Logan County": "Logan County"},
        "67762": {
            "Wallace County": "Wallace County",
            "Greeley County": "Greeley County",
            "Sherman County": "Sherman County",
        },
        "67764": {"Logan County": "Logan County", "Thomas County": "Thomas County"},
        "67801": {"Ford County": "Ford County", "Hodgeman County": "Hodgeman County", "Gray County": "Gray County"},
        "67831": {"Clark County": "Clark County"},
        "67834": {"Ford County": "Ford County", "Clark County": "Clark County", "Kiowa County": "Kiowa County"},
        "67835": {
            "Gray County": "Gray County",
            "Finney County": "Finney County",
            "Hodgeman County": "Hodgeman County",
            "Ford County": "Ford County",
        },
        "67836": {"Hamilton County": "Hamilton County"},
        "67837": {
            "Gray County": "Gray County",
            "Haskell County": "Haskell County",
            "Meade County": "Meade County",
            "Finney County": "Finney County",
        },
        "67838": {"Kearny County": "Kearny County", "Finney County": "Finney County"},
        "67839": {"Lane County": "Lane County", "Finney County": "Finney County"},
        "67840": {"Clark County": "Clark County"},
        "67841": {"Gray County": "Gray County", "Ford County": "Ford County", "Meade County": "Meade County"},
        "67842": {"Ford County": "Ford County", "Clark County": "Clark County"},
        "67843": {"Gray County": "Gray County"},
        "67844": {"Meade County": "Meade County", "Ford County": "Ford County", "Gray County": "Gray County"},
        "67846": {"Finney County": "Finney County", "Gray County": "Gray County", "Lane County": "Lane County"},
        "67849": {"Hodgeman County": "Hodgeman County"},
        "67850": {"Lane County": "Lane County", "Scott County": "Scott County"},
        "67851": {"Finney County": "Finney County", "Kearny County": "Kearny County", "Scott County": "Scott County"},
        "67853": {"Gray County": "Gray County", "Finney County": "Finney County"},
        "67854": {"Hodgeman County": "Hodgeman County"},
        "67855": {"Stanton County": "Stanton County", "Morton County": "Morton County", "Grant County": "Grant County"},
        "67857": {"Hamilton County": "Hamilton County"},
        "67859": {"Seward County": "Seward County"},
        "67860": {"Kearny County": "Kearny County", "Grant County": "Grant County"},
        "67861": {
            "Wichita County": "Wichita County",
            "Logan County": "Logan County",
            "Wallace County": "Wallace County",
        },
        "67862": {"Stanton County": "Stanton County", "Morton County": "Morton County"},
        "67863": {"Wichita County": "Wichita County", "Scott County": "Scott County"},
        "67864": {"Meade County": "Meade County"},
        "67865": {"Clark County": "Clark County", "Ford County": "Ford County"},
        "67867": {"Gray County": "Gray County", "Meade County": "Meade County"},
        "67868": {"Finney County": "Finney County", "Gray County": "Gray County"},
        "67869": {"Meade County": "Meade County", "Seward County": "Seward County"},
        "67870": {"Haskell County": "Haskell County", "Seward County": "Seward County", "Grant County": "Grant County"},
        "67871": {"Scott County": "Scott County", "Finney County": "Finney County", "Logan County": "Logan County"},
        "67876": {"Ford County": "Ford County", "Hodgeman County": "Hodgeman County"},
        "67877": {"Haskell County": "Haskell County", "Seward County": "Seward County"},
        "67878": {"Hamilton County": "Hamilton County", "Stanton County": "Stanton County"},
        "67879": {"Greeley County": "Greeley County", "Wichita County": "Wichita County"},
        "67880": {
            "Grant County": "Grant County",
            "Haskell County": "Haskell County",
            "Kearny County": "Kearny County",
            "Stanton County": "Stanton County",
        },
        "67882": {"Ford County": "Ford County"},
        "67901": {"Seward County": "Seward County"},
        "67950": {"Morton County": "Morton County"},
        "67951": {"Stevens County": "Stevens County", "Seward County": "Seward County"},
        "67952": {
            "Stevens County": "Stevens County",
            "Seward County": "Seward County",
            "Haskell County": "Haskell County",
        },
        "67953": {"Morton County": "Morton County", "Stevens County": "Stevens County"},
        "67954": {
            "Morton County": "Morton County",
            "Stevens County": "Stevens County",
            "Seward County": "Seward County",
        },
    }

    # ==========================================================================================
    # CATEGORY BENEFITS
    # Benefits shown on the "Do you already have any benefits?" step.
    # ==========================================================================================

    category_benefits = {
        "foodAndNutrition": {
            "benefits": {
                "snap": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.snap",
                        "_default_message": "Supplemental Nutrition Assistance Program (SNAP): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.snap_desc",
                        "_default_message": "Food assistance",
                    },
                },
                "wic": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.wic",
                        "_default_message": "Special Supplemental Nutrition Program for Women, Infants, and Children (WIC): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.wic_desc",
                        "_default_message": "Food and breastfeeding assistance",
                    },
                },
                "nslp": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.nslp",
                        "_default_message": "National School Lunch Program: ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.nslp_desc",
                        "_default_message": "Free school meals",
                    },
                },
            },
            "category_name": {
                "_label": "foodAndNutrition",
                "_default_message": "Food and Nutrition",
            },
        },
        "cash": {
            "benefits": {
                "ssdi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssdi",
                        "_default_message": "Social Security Disability Insurance (SSDI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssdi_desc",
                        "_default_message": "Social security benefit for people with disabilities",
                    },
                },
                "ssi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssi",
                        "_default_message": "Supplemental Security Income (SSI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssi_desc",
                        "_default_message": "Federal cash assistance for individuals who are disabled, blind, or 65 years of age or older",
                    },
                },
                "tanf": {
                    "name": {
                        "_label": "cashAssistanceBenefits.tanf",
                        "_default_message": "Temporary Assistance for Needy Families (TANF): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.tanf_desc",
                        "_default_message": "Cash assistance for families with children",
                    },
                },
            },
            "category_name": {
                "_label": "cashAssistance",
                "_default_message": "Cash Assistance",
            },
        },
        "healthCare": {
            "benefits": {
                "medicaid": {
                    "name": {
                        "_label": "healthCareBenefits.medicaid.ks",
                        "_default_message": "KanCare (Medicaid): ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.medicaid_desc",
                        "_default_message": "Free or low-cost health coverage",
                    },
                },
                "medicare_savings": {
                    "name": {
                        "_label": "healthCareBenefits.medicare_savings",
                        "_default_message": "Medicare Savings Program: ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.medicare_savings_desc",
                        "_default_message": "Help paying Medicare premiums and costs",
                    },
                },
            },
            "category_name": {
                "_label": "healthCare",
                "_default_message": "Health Care",
            },
        },
    }

    # ==========================================================================================
    # REFERRER DATA
    # ==========================================================================================

    # Inherit base referrer_data (favicon, noResultMessage, uiOptions, etc.) and
    # override only the keys KS customizes.
    referrer_data = {
        **ConfigurationData.referrer_data,
        # "uwgkc" is United Way of Greater Kansas City, whose 2-1-1 covers the metro on both sides
        # of the state line. The same referrer code is configured identically in mo.py, since each
        # state path loads its own config.
        "theme": {"default": "default", "uwgkc": "uwgkc"},
        "logoSource": {"default": "MFB_Logo", "uwgkc": "KS211_MFBLogo"},
        "logoAlt": {
            "default": {
                "id": "referrerHook.logoAlts.default",
                "defaultMessage": "MyFriendBen home page button",
            },
            "uwgkc": {
                "id": "referrerHook.logoAlts.ks211",
                "defaultMessage": "211 Kansas and MyFriendBen home page button",
            },
        },
        # `no_results_more_help` omits the Immediate Help tab from the results page. A named
        # referrer's list replaces `default` rather than merging with it, so every referrer
        # repeats the flag.
        # The co-branded logo's MyFriendBen wordmark is dark navy, which would disappear against
        # the theme's dark blue header, so this referrer gets the white header treatment.
        "uiOptions": {"default": ["no_results_more_help"], "uwgkc": ["no_results_more_help", "white_header"]},
        "logoFooterSource": {"default": "MFB_Logo"},
        "logoFooterAlt": {
            "default": {"id": "footer.logo.alt", "defaultMessage": "MFB Logo"},
        },
        "logoClass": {"default": "logo", "uwgkc": "uwgkc-logo-size"},
        "shareLink": {
            "default": "https://screener.myfriendben.org/ks/step-1",
            "uwgkc": "https://screener.myfriendben.org/ks/step-1?referrer=uwgkc",
        },
        "stateOptions": {"default": [], "uwgkc": ["ks", "mo"]},
        "stepDirectory": {
            "default": [
                "zipcode",
                # the hhSize and hhData have to be consecutive
                "householdSize",
                "householdData",
                "hasExpenses",
                "householdAssets",
                "hasBenefits",
                "acuteHHConditions",
                "referralSource",
                "signUpInfo",
            ],
        },
        "defaultLanguage": {"default": "en-us"},
        # Blank for uwgkc: its logo already carries "Kansas", so the header's separate state name
        # would repeat it underneath the artwork.
        "stateName": {"default": "Kansas", "uwgkc": ""},
    }
