from .base import ConfigurationData
from screener.models import WhiteLabel


class NjConfigurationData(ConfigurationData):
    @classmethod
    def get_white_label(self) -> WhiteLabel:
        return WhiteLabel.objects.get(code="nj")

    # ==========================================================================================
    # BASIC INFORMATION
    # ==========================================================================================

    # Pre-launch: reachable by direct link and by any referrer that names "nj" in stateOptions,
    # but not yet offered in the public state dropdown. Flip to True at launch.
    publicly_launched = False

    state = {"name": "New Jersey"}

    public_charge_rule = {
        "link": "https://www.uscis.gov/green-card/green-card-processes-and-procedures/public-charge",
        "text": {
            "_label": "landingPage.publicChargeLinkNJ",
            "_default_message": "U.S. Citizenship and Immigration Services",
        },
    }

    more_help_options = {
        "moreHelpOptions": [
            {
                "name": {
                    "_default_message": "New Jersey 211",
                    "_label": "moreHelp.211.name.nj",
                },
                "link": "https://www.nj211.org/",
                "phone": {
                    "_default_message": "Dial 2-1-1",
                    "_label": "moreHelp.211.phone.nj",
                },
            },
        ]
    }

    # ==========================================================================================
    # HEALTH INSURANCE OPTIONS
    # New Jersey's Medicaid and CHIP are both administered under the single "NJ FamilyCare" brand.
    # ==========================================================================================

    health_insurance_options = {
        "you": {
            **ConfigurationData.health_insurance_options["you"],
            "medicaid": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicaid.nj",
                    "_default_message": "NJ FamilyCare (Medicaid)",
                },
            },
            "chp": {
                "icon": {"_icon": "Chp", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.chp.nj",
                    "_default_message": "NJ FamilyCare (CHIP)",
                },
            },
        },
        "them": {
            **ConfigurationData.health_insurance_options["them"],
            "medicaid": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicaid.nj",
                    "_default_message": "NJ FamilyCare (Medicaid)",
                },
            },
            "chp": {
                "icon": {"_icon": "Chp", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.chp.nj",
                    "_default_message": "NJ FamilyCare (CHIP)",
                },
            },
        },
    }

    # ==========================================================================================
    # COUNTIES BY ZIPCODE
    # Source: HUD USPS ZIP-County crosswalk, 2026 Q3
    # vintage, downloaded from https://www.huduser.gov/apps/public/uspscrosswalk/login
    # Each zip is assigned to the single county with the highest tot_ratio (total address
    # share) per MFB-2161. Unlike mo.py/ks.py, this does not keep every nonzero-share county --
    # most of NJ's split zips are a >99% / <1% sliver pair, so a single best-match county avoids
    # cluttering the dropdown with near-meaningless choices.
    # ==========================================================================================

    counties_by_zipcode = {
        "07001": {"Middlesex County": "Middlesex County"},
        "07002": {"Hudson County": "Hudson County"},
        "07003": {"Essex County": "Essex County"},
        "07004": {"Essex County": "Essex County"},
        "07005": {"Morris County": "Morris County"},
        "07006": {"Essex County": "Essex County"},
        "07007": {"Essex County": "Essex County"},
        "07008": {"Middlesex County": "Middlesex County"},
        "07009": {"Essex County": "Essex County"},
        "07010": {"Bergen County": "Bergen County"},
        "07011": {"Passaic County": "Passaic County"},
        "07012": {"Passaic County": "Passaic County"},
        "07013": {"Passaic County": "Passaic County"},
        "07014": {"Passaic County": "Passaic County"},
        "07015": {"Passaic County": "Passaic County"},
        "07016": {"Union County": "Union County"},
        "07017": {"Essex County": "Essex County"},
        "07018": {"Essex County": "Essex County"},
        "07019": {"Essex County": "Essex County"},
        "07020": {"Bergen County": "Bergen County"},
        "07021": {"Essex County": "Essex County"},
        "07022": {"Bergen County": "Bergen County"},
        "07023": {"Union County": "Union County"},
        "07024": {"Bergen County": "Bergen County"},
        "07026": {"Bergen County": "Bergen County"},
        "07027": {"Union County": "Union County"},
        "07028": {"Essex County": "Essex County"},
        "07029": {"Hudson County": "Hudson County"},
        "07030": {"Hudson County": "Hudson County"},
        "07031": {"Bergen County": "Bergen County"},
        "07032": {"Hudson County": "Hudson County"},
        "07033": {"Union County": "Union County"},
        "07034": {"Morris County": "Morris County"},
        "07035": {"Morris County": "Morris County"},
        "07036": {"Union County": "Union County"},
        "07039": {"Essex County": "Essex County"},
        "07040": {"Essex County": "Essex County"},
        "07041": {"Essex County": "Essex County"},
        "07042": {"Essex County": "Essex County"},
        "07043": {"Essex County": "Essex County"},
        "07044": {"Essex County": "Essex County"},
        "07045": {"Morris County": "Morris County"},
        "07046": {"Morris County": "Morris County"},
        "07047": {"Hudson County": "Hudson County"},
        "07050": {"Essex County": "Essex County"},
        "07051": {"Essex County": "Essex County"},
        "07052": {"Essex County": "Essex County"},
        "07054": {"Morris County": "Morris County"},
        "07055": {"Passaic County": "Passaic County"},
        "07057": {"Bergen County": "Bergen County"},
        "07058": {"Morris County": "Morris County"},
        "07059": {"Somerset County": "Somerset County"},
        "07060": {"Union County": "Union County"},
        "07061": {"Union County": "Union County"},
        "07062": {"Union County": "Union County"},
        "07063": {"Union County": "Union County"},
        "07064": {"Middlesex County": "Middlesex County"},
        "07065": {"Union County": "Union County"},
        "07066": {"Union County": "Union County"},
        "07067": {"Middlesex County": "Middlesex County"},
        "07068": {"Essex County": "Essex County"},
        "07069": {"Somerset County": "Somerset County"},
        "07070": {"Bergen County": "Bergen County"},
        "07071": {"Bergen County": "Bergen County"},
        "07072": {"Bergen County": "Bergen County"},
        "07073": {"Bergen County": "Bergen County"},
        "07074": {"Bergen County": "Bergen County"},
        "07075": {"Bergen County": "Bergen County"},
        "07076": {"Union County": "Union County"},
        "07077": {"Middlesex County": "Middlesex County"},
        "07078": {"Essex County": "Essex County"},
        "07079": {"Essex County": "Essex County"},
        "07080": {"Middlesex County": "Middlesex County"},
        "07081": {"Union County": "Union County"},
        "07082": {"Morris County": "Morris County"},
        "07083": {"Union County": "Union County"},
        "07086": {"Hudson County": "Hudson County"},
        "07087": {"Hudson County": "Hudson County"},
        "07088": {"Union County": "Union County"},
        "07090": {"Union County": "Union County"},
        "07091": {"Union County": "Union County"},
        "07092": {"Union County": "Union County"},
        "07093": {"Hudson County": "Hudson County"},
        "07094": {"Hudson County": "Hudson County"},
        "07095": {"Middlesex County": "Middlesex County"},
        "07096": {"Hudson County": "Hudson County"},
        "07097": {"Hudson County": "Hudson County"},
        "07099": {"Hudson County": "Hudson County"},
        "07101": {"Essex County": "Essex County"},
        "07102": {"Essex County": "Essex County"},
        "07103": {"Essex County": "Essex County"},
        "07104": {"Essex County": "Essex County"},
        "07105": {"Essex County": "Essex County"},
        "07106": {"Essex County": "Essex County"},
        "07107": {"Essex County": "Essex County"},
        "07108": {"Essex County": "Essex County"},
        "07109": {"Essex County": "Essex County"},
        "07110": {"Essex County": "Essex County"},
        "07111": {"Essex County": "Essex County"},
        "07112": {"Essex County": "Essex County"},
        "07114": {"Essex County": "Essex County"},
        "07175": {"Essex County": "Essex County"},
        "07201": {"Union County": "Union County"},
        "07202": {"Union County": "Union County"},
        "07203": {"Union County": "Union County"},
        "07204": {"Union County": "Union County"},
        "07205": {"Union County": "Union County"},
        "07206": {"Union County": "Union County"},
        "07207": {"Union County": "Union County"},
        "07208": {"Union County": "Union County"},
        "07302": {"Hudson County": "Hudson County"},
        "07303": {"Hudson County": "Hudson County"},
        "07304": {"Hudson County": "Hudson County"},
        "07305": {"Hudson County": "Hudson County"},
        "07306": {"Hudson County": "Hudson County"},
        "07307": {"Hudson County": "Hudson County"},
        "07310": {"Hudson County": "Hudson County"},
        "07311": {"Hudson County": "Hudson County"},
        "07399": {"Hudson County": "Hudson County"},
        "07401": {"Bergen County": "Bergen County"},
        "07403": {"Passaic County": "Passaic County"},
        "07405": {"Morris County": "Morris County"},
        "07407": {"Bergen County": "Bergen County"},
        "07410": {"Bergen County": "Bergen County"},
        "07416": {"Sussex County": "Sussex County"},
        "07417": {"Bergen County": "Bergen County"},
        "07418": {"Sussex County": "Sussex County"},
        "07419": {"Sussex County": "Sussex County"},
        "07420": {"Passaic County": "Passaic County"},
        "07421": {"Passaic County": "Passaic County"},
        "07422": {"Sussex County": "Sussex County"},
        "07423": {"Bergen County": "Bergen County"},
        "07424": {"Passaic County": "Passaic County"},
        "07428": {"Sussex County": "Sussex County"},
        "07430": {"Bergen County": "Bergen County"},
        "07432": {"Bergen County": "Bergen County"},
        "07435": {"Morris County": "Morris County"},
        "07436": {"Bergen County": "Bergen County"},
        "07438": {"Morris County": "Morris County"},
        "07439": {"Sussex County": "Sussex County"},
        "07440": {"Morris County": "Morris County"},
        "07442": {"Passaic County": "Passaic County"},
        "07444": {"Morris County": "Morris County"},
        "07446": {"Bergen County": "Bergen County"},
        "07450": {"Bergen County": "Bergen County"},
        "07451": {"Bergen County": "Bergen County"},
        "07452": {"Bergen County": "Bergen County"},
        "07456": {"Passaic County": "Passaic County"},
        "07457": {"Morris County": "Morris County"},
        "07458": {"Bergen County": "Bergen County"},
        "07460": {"Sussex County": "Sussex County"},
        "07461": {"Sussex County": "Sussex County"},
        "07462": {"Sussex County": "Sussex County"},
        "07463": {"Bergen County": "Bergen County"},
        "07465": {"Passaic County": "Passaic County"},
        "07470": {"Passaic County": "Passaic County"},
        "07474": {"Passaic County": "Passaic County"},
        "07480": {"Passaic County": "Passaic County"},
        "07481": {"Bergen County": "Bergen County"},
        "07495": {"Bergen County": "Bergen County"},
        "07501": {"Passaic County": "Passaic County"},
        "07502": {"Passaic County": "Passaic County"},
        "07503": {"Passaic County": "Passaic County"},
        "07504": {"Passaic County": "Passaic County"},
        "07505": {"Passaic County": "Passaic County"},
        "07506": {"Passaic County": "Passaic County"},
        "07507": {"Passaic County": "Passaic County"},
        "07508": {"Passaic County": "Passaic County"},
        "07509": {"Passaic County": "Passaic County"},
        "07510": {"Passaic County": "Passaic County"},
        "07511": {"Passaic County": "Passaic County"},
        "07512": {"Passaic County": "Passaic County"},
        "07513": {"Passaic County": "Passaic County"},
        "07514": {"Passaic County": "Passaic County"},
        "07522": {"Passaic County": "Passaic County"},
        "07524": {"Passaic County": "Passaic County"},
        "07538": {"Passaic County": "Passaic County"},
        "07543": {"Passaic County": "Passaic County"},
        "07544": {"Passaic County": "Passaic County"},
        "07601": {"Bergen County": "Bergen County"},
        "07602": {"Bergen County": "Bergen County"},
        "07603": {"Bergen County": "Bergen County"},
        "07604": {"Bergen County": "Bergen County"},
        "07605": {"Bergen County": "Bergen County"},
        "07606": {"Bergen County": "Bergen County"},
        "07607": {"Bergen County": "Bergen County"},
        "07608": {"Bergen County": "Bergen County"},
        "07620": {"Bergen County": "Bergen County"},
        "07621": {"Bergen County": "Bergen County"},
        "07624": {"Bergen County": "Bergen County"},
        "07626": {"Bergen County": "Bergen County"},
        "07627": {"Bergen County": "Bergen County"},
        "07628": {"Bergen County": "Bergen County"},
        "07630": {"Bergen County": "Bergen County"},
        "07631": {"Bergen County": "Bergen County"},
        "07632": {"Bergen County": "Bergen County"},
        "07640": {"Bergen County": "Bergen County"},
        "07641": {"Bergen County": "Bergen County"},
        "07642": {"Bergen County": "Bergen County"},
        "07643": {"Bergen County": "Bergen County"},
        "07644": {"Bergen County": "Bergen County"},
        "07645": {"Bergen County": "Bergen County"},
        "07646": {"Bergen County": "Bergen County"},
        "07647": {"Bergen County": "Bergen County"},
        "07648": {"Bergen County": "Bergen County"},
        "07649": {"Bergen County": "Bergen County"},
        "07650": {"Bergen County": "Bergen County"},
        "07652": {"Bergen County": "Bergen County"},
        "07653": {"Bergen County": "Bergen County"},
        "07656": {"Bergen County": "Bergen County"},
        "07657": {"Bergen County": "Bergen County"},
        "07660": {"Bergen County": "Bergen County"},
        "07661": {"Bergen County": "Bergen County"},
        "07662": {"Bergen County": "Bergen County"},
        "07663": {"Bergen County": "Bergen County"},
        "07666": {"Bergen County": "Bergen County"},
        "07670": {"Bergen County": "Bergen County"},
        "07675": {"Bergen County": "Bergen County"},
        "07676": {"Bergen County": "Bergen County"},
        "07677": {"Bergen County": "Bergen County"},
        "07699": {"Bergen County": "Bergen County"},
        "07701": {"Monmouth County": "Monmouth County"},
        "07702": {"Monmouth County": "Monmouth County"},
        "07704": {"Monmouth County": "Monmouth County"},
        "07710": {"Monmouth County": "Monmouth County"},
        "07711": {"Monmouth County": "Monmouth County"},
        "07712": {"Monmouth County": "Monmouth County"},
        "07716": {"Monmouth County": "Monmouth County"},
        "07717": {"Monmouth County": "Monmouth County"},
        "07718": {"Monmouth County": "Monmouth County"},
        "07719": {"Monmouth County": "Monmouth County"},
        "07720": {"Monmouth County": "Monmouth County"},
        "07721": {"Monmouth County": "Monmouth County"},
        "07722": {"Monmouth County": "Monmouth County"},
        "07723": {"Monmouth County": "Monmouth County"},
        "07724": {"Monmouth County": "Monmouth County"},
        "07726": {"Monmouth County": "Monmouth County"},
        "07727": {"Monmouth County": "Monmouth County"},
        "07728": {"Monmouth County": "Monmouth County"},
        "07730": {"Monmouth County": "Monmouth County"},
        "07731": {"Monmouth County": "Monmouth County"},
        "07732": {"Monmouth County": "Monmouth County"},
        "07733": {"Monmouth County": "Monmouth County"},
        "07734": {"Monmouth County": "Monmouth County"},
        "07735": {"Monmouth County": "Monmouth County"},
        "07737": {"Monmouth County": "Monmouth County"},
        "07738": {"Monmouth County": "Monmouth County"},
        "07739": {"Monmouth County": "Monmouth County"},
        "07740": {"Monmouth County": "Monmouth County"},
        "07746": {"Monmouth County": "Monmouth County"},
        "07747": {"Monmouth County": "Monmouth County"},
        "07748": {"Monmouth County": "Monmouth County"},
        "07750": {"Monmouth County": "Monmouth County"},
        "07751": {"Monmouth County": "Monmouth County"},
        "07752": {"Monmouth County": "Monmouth County"},
        "07753": {"Monmouth County": "Monmouth County"},
        "07754": {"Monmouth County": "Monmouth County"},
        "07755": {"Monmouth County": "Monmouth County"},
        "07756": {"Monmouth County": "Monmouth County"},
        "07757": {"Monmouth County": "Monmouth County"},
        "07758": {"Monmouth County": "Monmouth County"},
        "07760": {"Monmouth County": "Monmouth County"},
        "07762": {"Monmouth County": "Monmouth County"},
        "07763": {"Monmouth County": "Monmouth County"},
        "07764": {"Monmouth County": "Monmouth County"},
        "07765": {"Monmouth County": "Monmouth County"},
        "07799": {"Monmouth County": "Monmouth County"},
        "07801": {"Morris County": "Morris County"},
        "07802": {"Morris County": "Morris County"},
        "07803": {"Morris County": "Morris County"},
        "07806": {"Morris County": "Morris County"},
        "07820": {"Warren County": "Warren County"},
        "07821": {"Sussex County": "Sussex County"},
        "07822": {"Sussex County": "Sussex County"},
        "07823": {"Warren County": "Warren County"},
        "07825": {"Warren County": "Warren County"},
        "07826": {"Sussex County": "Sussex County"},
        "07827": {"Sussex County": "Sussex County"},
        "07828": {"Morris County": "Morris County"},
        "07830": {"Hunterdon County": "Hunterdon County"},
        "07831": {"Hunterdon County": "Hunterdon County"},
        "07832": {"Warren County": "Warren County"},
        "07833": {"Warren County": "Warren County"},
        "07834": {"Morris County": "Morris County"},
        "07836": {"Morris County": "Morris County"},
        "07837": {"Sussex County": "Sussex County"},
        "07838": {"Warren County": "Warren County"},
        "07839": {"Sussex County": "Sussex County"},
        "07840": {"Warren County": "Warren County"},
        "07842": {"Morris County": "Morris County"},
        "07843": {"Sussex County": "Sussex County"},
        "07844": {"Warren County": "Warren County"},
        "07845": {"Morris County": "Morris County"},
        "07846": {"Warren County": "Warren County"},
        "07847": {"Morris County": "Morris County"},
        "07848": {"Sussex County": "Sussex County"},
        "07849": {"Morris County": "Morris County"},
        "07850": {"Morris County": "Morris County"},
        "07851": {"Sussex County": "Sussex County"},
        "07852": {"Morris County": "Morris County"},
        "07853": {"Morris County": "Morris County"},
        "07855": {"Sussex County": "Sussex County"},
        "07856": {"Morris County": "Morris County"},
        "07857": {"Morris County": "Morris County"},
        "07860": {"Sussex County": "Sussex County"},
        "07863": {"Warren County": "Warren County"},
        "07865": {"Warren County": "Warren County"},
        "07866": {"Morris County": "Morris County"},
        "07869": {"Morris County": "Morris County"},
        "07870": {"Morris County": "Morris County"},
        "07871": {"Sussex County": "Sussex County"},
        "07874": {"Sussex County": "Sussex County"},
        "07875": {"Sussex County": "Sussex County"},
        "07876": {"Morris County": "Morris County"},
        "07877": {"Sussex County": "Sussex County"},
        "07878": {"Morris County": "Morris County"},
        "07879": {"Sussex County": "Sussex County"},
        "07880": {"Warren County": "Warren County"},
        "07882": {"Warren County": "Warren County"},
        "07885": {"Morris County": "Morris County"},
        "07890": {"Sussex County": "Sussex County"},
        "07901": {"Union County": "Union County"},
        "07902": {"Union County": "Union County"},
        "07920": {"Somerset County": "Somerset County"},
        "07921": {"Somerset County": "Somerset County"},
        "07922": {"Union County": "Union County"},
        "07924": {"Somerset County": "Somerset County"},
        "07926": {"Morris County": "Morris County"},
        "07927": {"Morris County": "Morris County"},
        "07928": {"Morris County": "Morris County"},
        "07930": {"Morris County": "Morris County"},
        "07931": {"Somerset County": "Somerset County"},
        "07932": {"Morris County": "Morris County"},
        "07933": {"Morris County": "Morris County"},
        "07934": {"Somerset County": "Somerset County"},
        "07935": {"Morris County": "Morris County"},
        "07936": {"Morris County": "Morris County"},
        "07938": {"Somerset County": "Somerset County"},
        "07939": {"Somerset County": "Somerset County"},
        "07940": {"Morris County": "Morris County"},
        "07945": {"Morris County": "Morris County"},
        "07946": {"Morris County": "Morris County"},
        "07950": {"Morris County": "Morris County"},
        "07960": {"Morris County": "Morris County"},
        "07961": {"Morris County": "Morris County"},
        "07962": {"Morris County": "Morris County"},
        "07963": {"Morris County": "Morris County"},
        "07970": {"Morris County": "Morris County"},
        "07974": {"Union County": "Union County"},
        "07976": {"Morris County": "Morris County"},
        "07977": {"Somerset County": "Somerset County"},
        "07978": {"Somerset County": "Somerset County"},
        "07979": {"Hunterdon County": "Hunterdon County"},
        "07980": {"Morris County": "Morris County"},
        "07981": {"Morris County": "Morris County"},
        "08001": {"Salem County": "Salem County"},
        "08002": {"Camden County": "Camden County"},
        "08003": {"Camden County": "Camden County"},
        "08004": {"Camden County": "Camden County"},
        "08005": {"Ocean County": "Ocean County"},
        "08006": {"Ocean County": "Ocean County"},
        "08007": {"Camden County": "Camden County"},
        "08008": {"Ocean County": "Ocean County"},
        "08009": {"Camden County": "Camden County"},
        "08010": {"Burlington County": "Burlington County"},
        "08011": {"Burlington County": "Burlington County"},
        "08012": {"Camden County": "Camden County"},
        "08014": {"Gloucester County": "Gloucester County"},
        "08015": {"Burlington County": "Burlington County"},
        "08016": {"Burlington County": "Burlington County"},
        "08018": {"Camden County": "Camden County"},
        "08019": {"Burlington County": "Burlington County"},
        "08020": {"Gloucester County": "Gloucester County"},
        "08021": {"Camden County": "Camden County"},
        "08022": {"Burlington County": "Burlington County"},
        "08023": {"Salem County": "Salem County"},
        "08025": {"Gloucester County": "Gloucester County"},
        "08026": {"Camden County": "Camden County"},
        "08027": {"Gloucester County": "Gloucester County"},
        "08028": {"Gloucester County": "Gloucester County"},
        "08029": {"Camden County": "Camden County"},
        "08030": {"Camden County": "Camden County"},
        "08031": {"Camden County": "Camden County"},
        "08032": {"Gloucester County": "Gloucester County"},
        "08033": {"Camden County": "Camden County"},
        "08034": {"Camden County": "Camden County"},
        "08035": {"Camden County": "Camden County"},
        "08036": {"Burlington County": "Burlington County"},
        "08037": {"Atlantic County": "Atlantic County"},
        "08038": {"Salem County": "Salem County"},
        "08039": {"Gloucester County": "Gloucester County"},
        "08041": {"Burlington County": "Burlington County"},
        "08042": {"Burlington County": "Burlington County"},
        "08043": {"Camden County": "Camden County"},
        "08045": {"Camden County": "Camden County"},
        "08046": {"Burlington County": "Burlington County"},
        "08048": {"Burlington County": "Burlington County"},
        "08049": {"Camden County": "Camden County"},
        "08050": {"Ocean County": "Ocean County"},
        "08051": {"Gloucester County": "Gloucester County"},
        "08052": {"Burlington County": "Burlington County"},
        "08053": {"Burlington County": "Burlington County"},
        "08054": {"Burlington County": "Burlington County"},
        "08055": {"Burlington County": "Burlington County"},
        "08056": {"Gloucester County": "Gloucester County"},
        "08057": {"Burlington County": "Burlington County"},
        "08059": {"Camden County": "Camden County"},
        "08060": {"Burlington County": "Burlington County"},
        "08061": {"Gloucester County": "Gloucester County"},
        "08062": {"Gloucester County": "Gloucester County"},
        "08063": {"Gloucester County": "Gloucester County"},
        "08064": {"Burlington County": "Burlington County"},
        "08065": {"Burlington County": "Burlington County"},
        "08066": {"Gloucester County": "Gloucester County"},
        "08067": {"Salem County": "Salem County"},
        "08068": {"Burlington County": "Burlington County"},
        "08069": {"Salem County": "Salem County"},
        "08070": {"Salem County": "Salem County"},
        "08071": {"Gloucester County": "Gloucester County"},
        "08072": {"Salem County": "Salem County"},
        "08073": {"Burlington County": "Burlington County"},
        "08074": {"Gloucester County": "Gloucester County"},
        "08075": {"Burlington County": "Burlington County"},
        "08077": {"Burlington County": "Burlington County"},
        "08078": {"Camden County": "Camden County"},
        "08079": {"Salem County": "Salem County"},
        "08080": {"Gloucester County": "Gloucester County"},
        "08081": {"Camden County": "Camden County"},
        "08083": {"Camden County": "Camden County"},
        "08084": {"Camden County": "Camden County"},
        "08085": {"Gloucester County": "Gloucester County"},
        "08086": {"Gloucester County": "Gloucester County"},
        "08087": {"Ocean County": "Ocean County"},
        "08088": {"Burlington County": "Burlington County"},
        "08089": {"Camden County": "Camden County"},
        "08090": {"Gloucester County": "Gloucester County"},
        "08091": {"Camden County": "Camden County"},
        "08092": {"Ocean County": "Ocean County"},
        "08093": {"Gloucester County": "Gloucester County"},
        "08094": {"Gloucester County": "Gloucester County"},
        "08095": {"Camden County": "Camden County"},
        "08096": {"Gloucester County": "Gloucester County"},
        "08097": {"Gloucester County": "Gloucester County"},
        "08098": {"Salem County": "Salem County"},
        "08099": {"Camden County": "Camden County"},
        "08101": {"Camden County": "Camden County"},
        "08102": {"Camden County": "Camden County"},
        "08103": {"Camden County": "Camden County"},
        "08104": {"Camden County": "Camden County"},
        "08105": {"Camden County": "Camden County"},
        "08106": {"Camden County": "Camden County"},
        "08107": {"Camden County": "Camden County"},
        "08108": {"Camden County": "Camden County"},
        "08109": {"Camden County": "Camden County"},
        "08110": {"Camden County": "Camden County"},
        "08201": {"Atlantic County": "Atlantic County"},
        "08202": {"Cape May County": "Cape May County"},
        "08203": {"Atlantic County": "Atlantic County"},
        "08204": {"Cape May County": "Cape May County"},
        "08205": {"Atlantic County": "Atlantic County"},
        "08210": {"Cape May County": "Cape May County"},
        "08212": {"Cape May County": "Cape May County"},
        "08213": {"Atlantic County": "Atlantic County"},
        "08214": {"Cape May County": "Cape May County"},
        "08215": {"Atlantic County": "Atlantic County"},
        "08217": {"Atlantic County": "Atlantic County"},
        "08218": {"Cape May County": "Cape May County"},
        "08219": {"Cape May County": "Cape May County"},
        "08220": {"Atlantic County": "Atlantic County"},
        "08221": {"Atlantic County": "Atlantic County"},
        "08223": {"Cape May County": "Cape May County"},
        "08224": {"Burlington County": "Burlington County"},
        "08225": {"Atlantic County": "Atlantic County"},
        "08226": {"Cape May County": "Cape May County"},
        "08230": {"Cape May County": "Cape May County"},
        "08231": {"Atlantic County": "Atlantic County"},
        "08232": {"Atlantic County": "Atlantic County"},
        "08234": {"Atlantic County": "Atlantic County"},
        "08240": {"Atlantic County": "Atlantic County"},
        "08241": {"Atlantic County": "Atlantic County"},
        "08242": {"Cape May County": "Cape May County"},
        "08243": {"Cape May County": "Cape May County"},
        "08244": {"Atlantic County": "Atlantic County"},
        "08245": {"Cape May County": "Cape May County"},
        "08246": {"Cape May County": "Cape May County"},
        "08247": {"Cape May County": "Cape May County"},
        "08248": {"Cape May County": "Cape May County"},
        "08250": {"Cape May County": "Cape May County"},
        "08251": {"Cape May County": "Cape May County"},
        "08252": {"Cape May County": "Cape May County"},
        "08260": {"Cape May County": "Cape May County"},
        "08270": {"Cape May County": "Cape May County"},
        "08302": {"Cumberland County": "Cumberland County"},
        "08310": {"Atlantic County": "Atlantic County"},
        "08311": {"Cumberland County": "Cumberland County"},
        "08312": {"Gloucester County": "Gloucester County"},
        "08313": {"Cumberland County": "Cumberland County"},
        "08314": {"Cumberland County": "Cumberland County"},
        "08315": {"Cumberland County": "Cumberland County"},
        "08316": {"Cumberland County": "Cumberland County"},
        "08317": {"Atlantic County": "Atlantic County"},
        "08318": {"Salem County": "Salem County"},
        "08319": {"Atlantic County": "Atlantic County"},
        "08320": {"Cumberland County": "Cumberland County"},
        "08321": {"Cumberland County": "Cumberland County"},
        "08322": {"Gloucester County": "Gloucester County"},
        "08323": {"Cumberland County": "Cumberland County"},
        "08324": {"Cumberland County": "Cumberland County"},
        "08326": {"Atlantic County": "Atlantic County"},
        "08327": {"Cumberland County": "Cumberland County"},
        "08328": {"Gloucester County": "Gloucester County"},
        "08329": {"Cumberland County": "Cumberland County"},
        "08330": {"Atlantic County": "Atlantic County"},
        "08332": {"Cumberland County": "Cumberland County"},
        "08340": {"Atlantic County": "Atlantic County"},
        "08341": {"Atlantic County": "Atlantic County"},
        "08342": {"Atlantic County": "Atlantic County"},
        "08343": {"Gloucester County": "Gloucester County"},
        "08344": {"Gloucester County": "Gloucester County"},
        "08345": {"Cumberland County": "Cumberland County"},
        "08346": {"Atlantic County": "Atlantic County"},
        "08347": {"Salem County": "Salem County"},
        "08348": {"Cumberland County": "Cumberland County"},
        "08349": {"Cumberland County": "Cumberland County"},
        "08350": {"Atlantic County": "Atlantic County"},
        "08352": {"Cumberland County": "Cumberland County"},
        "08353": {"Cumberland County": "Cumberland County"},
        "08360": {"Cumberland County": "Cumberland County"},
        "08361": {"Cumberland County": "Cumberland County"},
        "08362": {"Cumberland County": "Cumberland County"},
        "08401": {"Atlantic County": "Atlantic County"},
        "08402": {"Atlantic County": "Atlantic County"},
        "08403": {"Atlantic County": "Atlantic County"},
        "08404": {"Atlantic County": "Atlantic County"},
        "08405": {"Atlantic County": "Atlantic County"},
        "08406": {"Atlantic County": "Atlantic County"},
        "08501": {"Monmouth County": "Monmouth County"},
        "08502": {"Somerset County": "Somerset County"},
        "08504": {"Somerset County": "Somerset County"},
        "08505": {"Burlington County": "Burlington County"},
        "08510": {"Monmouth County": "Monmouth County"},
        "08511": {"Burlington County": "Burlington County"},
        "08512": {"Middlesex County": "Middlesex County"},
        "08514": {"Monmouth County": "Monmouth County"},
        "08515": {"Burlington County": "Burlington County"},
        "08518": {"Burlington County": "Burlington County"},
        "08520": {"Mercer County": "Mercer County"},
        "08525": {"Mercer County": "Mercer County"},
        "08527": {"Ocean County": "Ocean County"},
        "08528": {"Somerset County": "Somerset County"},
        "08530": {"Hunterdon County": "Hunterdon County"},
        "08533": {"Ocean County": "Ocean County"},
        "08534": {"Mercer County": "Mercer County"},
        "08535": {"Monmouth County": "Monmouth County"},
        "08536": {"Middlesex County": "Middlesex County"},
        "08540": {"Mercer County": "Mercer County"},
        "08542": {"Mercer County": "Mercer County"},
        "08543": {"Mercer County": "Mercer County"},
        "08544": {"Mercer County": "Mercer County"},
        "08550": {"Mercer County": "Mercer County"},
        "08551": {"Hunterdon County": "Hunterdon County"},
        "08553": {"Somerset County": "Somerset County"},
        "08554": {"Burlington County": "Burlington County"},
        "08555": {"Monmouth County": "Monmouth County"},
        "08556": {"Hunterdon County": "Hunterdon County"},
        "08557": {"Hunterdon County": "Hunterdon County"},
        "08558": {"Somerset County": "Somerset County"},
        "08559": {"Hunterdon County": "Hunterdon County"},
        "08560": {"Mercer County": "Mercer County"},
        "08561": {"Mercer County": "Mercer County"},
        "08562": {"Burlington County": "Burlington County"},
        "08601": {"Mercer County": "Mercer County"},
        "08602": {"Mercer County": "Mercer County"},
        "08603": {"Mercer County": "Mercer County"},
        "08604": {"Mercer County": "Mercer County"},
        "08605": {"Mercer County": "Mercer County"},
        "08606": {"Mercer County": "Mercer County"},
        "08607": {"Mercer County": "Mercer County"},
        "08608": {"Mercer County": "Mercer County"},
        "08609": {"Mercer County": "Mercer County"},
        "08610": {"Mercer County": "Mercer County"},
        "08611": {"Mercer County": "Mercer County"},
        "08618": {"Mercer County": "Mercer County"},
        "08619": {"Mercer County": "Mercer County"},
        "08620": {"Mercer County": "Mercer County"},
        "08628": {"Mercer County": "Mercer County"},
        "08629": {"Mercer County": "Mercer County"},
        "08638": {"Mercer County": "Mercer County"},
        "08640": {"Burlington County": "Burlington County"},
        "08641": {"Burlington County": "Burlington County"},
        "08648": {"Mercer County": "Mercer County"},
        "08650": {"Mercer County": "Mercer County"},
        "08690": {"Mercer County": "Mercer County"},
        "08691": {"Mercer County": "Mercer County"},
        "08701": {"Ocean County": "Ocean County"},
        "08720": {"Monmouth County": "Monmouth County"},
        "08721": {"Ocean County": "Ocean County"},
        "08722": {"Ocean County": "Ocean County"},
        "08723": {"Ocean County": "Ocean County"},
        "08724": {"Ocean County": "Ocean County"},
        "08730": {"Monmouth County": "Monmouth County"},
        "08731": {"Ocean County": "Ocean County"},
        "08732": {"Ocean County": "Ocean County"},
        "08733": {"Ocean County": "Ocean County"},
        "08734": {"Ocean County": "Ocean County"},
        "08735": {"Ocean County": "Ocean County"},
        "08736": {"Monmouth County": "Monmouth County"},
        "08738": {"Ocean County": "Ocean County"},
        "08739": {"Ocean County": "Ocean County"},
        "08740": {"Ocean County": "Ocean County"},
        "08741": {"Ocean County": "Ocean County"},
        "08742": {"Ocean County": "Ocean County"},
        "08750": {"Monmouth County": "Monmouth County"},
        "08751": {"Ocean County": "Ocean County"},
        "08752": {"Ocean County": "Ocean County"},
        "08753": {"Ocean County": "Ocean County"},
        "08754": {"Ocean County": "Ocean County"},
        "08755": {"Ocean County": "Ocean County"},
        "08757": {"Ocean County": "Ocean County"},
        "08758": {"Ocean County": "Ocean County"},
        "08759": {"Ocean County": "Ocean County"},
        "08801": {"Hunterdon County": "Hunterdon County"},
        "08802": {"Hunterdon County": "Hunterdon County"},
        "08803": {"Hunterdon County": "Hunterdon County"},
        "08804": {"Hunterdon County": "Hunterdon County"},
        "08805": {"Somerset County": "Somerset County"},
        "08807": {"Somerset County": "Somerset County"},
        "08808": {"Warren County": "Warren County"},
        "08809": {"Hunterdon County": "Hunterdon County"},
        "08810": {"Middlesex County": "Middlesex County"},
        "08812": {"Middlesex County": "Middlesex County"},
        "08816": {"Middlesex County": "Middlesex County"},
        "08817": {"Middlesex County": "Middlesex County"},
        "08818": {"Middlesex County": "Middlesex County"},
        "08820": {"Middlesex County": "Middlesex County"},
        "08821": {"Somerset County": "Somerset County"},
        "08822": {"Hunterdon County": "Hunterdon County"},
        "08823": {"Somerset County": "Somerset County"},
        "08824": {"Middlesex County": "Middlesex County"},
        "08825": {"Hunterdon County": "Hunterdon County"},
        "08826": {"Hunterdon County": "Hunterdon County"},
        "08827": {"Hunterdon County": "Hunterdon County"},
        "08828": {"Middlesex County": "Middlesex County"},
        "08829": {"Hunterdon County": "Hunterdon County"},
        "08830": {"Middlesex County": "Middlesex County"},
        "08831": {"Middlesex County": "Middlesex County"},
        "08832": {"Middlesex County": "Middlesex County"},
        "08833": {"Hunterdon County": "Hunterdon County"},
        "08835": {"Somerset County": "Somerset County"},
        "08836": {"Somerset County": "Somerset County"},
        "08837": {"Middlesex County": "Middlesex County"},
        "08840": {"Middlesex County": "Middlesex County"},
        "08844": {"Somerset County": "Somerset County"},
        "08846": {"Middlesex County": "Middlesex County"},
        "08848": {"Hunterdon County": "Hunterdon County"},
        "08850": {"Middlesex County": "Middlesex County"},
        "08852": {"Middlesex County": "Middlesex County"},
        "08853": {"Somerset County": "Somerset County"},
        "08854": {"Middlesex County": "Middlesex County"},
        "08855": {"Middlesex County": "Middlesex County"},
        "08857": {"Middlesex County": "Middlesex County"},
        "08858": {"Hunterdon County": "Hunterdon County"},
        "08859": {"Middlesex County": "Middlesex County"},
        "08861": {"Middlesex County": "Middlesex County"},
        "08862": {"Middlesex County": "Middlesex County"},
        "08863": {"Middlesex County": "Middlesex County"},
        "08865": {"Warren County": "Warren County"},
        "08867": {"Hunterdon County": "Hunterdon County"},
        "08868": {"Hunterdon County": "Hunterdon County"},
        "08869": {"Somerset County": "Somerset County"},
        "08870": {"Hunterdon County": "Hunterdon County"},
        "08872": {"Middlesex County": "Middlesex County"},
        "08873": {"Somerset County": "Somerset County"},
        "08875": {"Somerset County": "Somerset County"},
        "08876": {"Somerset County": "Somerset County"},
        "08879": {"Middlesex County": "Middlesex County"},
        "08880": {"Somerset County": "Somerset County"},
        "08882": {"Middlesex County": "Middlesex County"},
        "08884": {"Middlesex County": "Middlesex County"},
        "08885": {"Hunterdon County": "Hunterdon County"},
        "08886": {"Warren County": "Warren County"},
        "08887": {"Hunterdon County": "Hunterdon County"},
        "08888": {"Hunterdon County": "Hunterdon County"},
        "08889": {"Hunterdon County": "Hunterdon County"},
        "08899": {"Middlesex County": "Middlesex County"},
        "08901": {"Middlesex County": "Middlesex County"},
        "08902": {"Middlesex County": "Middlesex County"},
        "08903": {"Middlesex County": "Middlesex County"},
        "08904": {"Middlesex County": "Middlesex County"},
        "08906": {"Middlesex County": "Middlesex County"},
        "08933": {"Middlesex County": "Middlesex County"},
    }

    # ==========================================================================================
    # CATEGORY BENEFITS
    # Benefits shown on the "Do you already have any benefits?" step.
    # ==========================================================================================

    category_benefits = {
        "foodAndNutrition": {
            "benefits": {
                "snap": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.snap",
                        "_default_message": "Supplemental Nutrition Assistance Program (SNAP): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.snap_desc",
                        "_default_message": "Food assistance",
                    },
                },
                "wic": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.wic",
                        "_default_message": "Special Supplemental Nutrition Program for Women, Infants, and Children (WIC): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.wic_desc",
                        "_default_message": "Food and breastfeeding assistance",
                    },
                },
                "nslp": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.nslp",
                        "_default_message": "National School Lunch Program: ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.nslp_desc",
                        "_default_message": "Free school meals",
                    },
                },
            },
            "category_name": {
                "_label": "foodAndNutrition",
                "_default_message": "Food and Nutrition",
            },
        },
        "cash": {
            "benefits": {
                "ssdi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssdi",
                        "_default_message": "Social Security Disability Insurance (SSDI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssdi_desc",
                        "_default_message": "Social security benefit for people with disabilities",
                    },
                },
                "ssi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssi",
                        "_default_message": "Supplemental Security Income (SSI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssi_desc",
                        "_default_message": "Federal cash assistance for individuals who are disabled, blind, or 65 years of age or older",
                    },
                },
                "tanf": {
                    "name": {
                        "_label": "cashAssistanceBenefits.tanf",
                        "_default_message": "Temporary Assistance for Needy Families (TANF): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.tanf_desc",
                        "_default_message": "Cash assistance for families with children",
                    },
                },
            },
            "category_name": {
                "_label": "cashAssistance",
                "_default_message": "Cash Assistance",
            },
        },
        "healthCare": {
            "benefits": {
                "medicaid": {
                    "name": {
                        "_label": "healthCareBenefits.medicaid.nj",
                        "_default_message": "NJ FamilyCare (Medicaid): ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.medicaid_desc",
                        "_default_message": "Free or low-cost health coverage",
                    },
                },
                "chp": {
                    "name": {
                        "_label": "healthCareBenefits.chp.nj",
                        "_default_message": "NJ FamilyCare (CHIP): ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.chp_desc",
                        "_default_message": "Free or low-cost health coverage for children",
                    },
                },
                "medicare_savings": {
                    "name": {
                        "_label": "healthCareBenefits.medicare_savings",
                        "_default_message": "Medicare Savings Program: ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.medicare_savings_desc",
                        "_default_message": "Help paying Medicare premiums and costs",
                    },
                },
            },
            "category_name": {
                "_label": "healthCare",
                "_default_message": "Health Care",
            },
        },
    }

    # ==========================================================================================
    # REFERRER DATA
    # ==========================================================================================

    # NJ uses generic MFB branding and the default step directory, so it inherits everything
    # from base and overrides only the values that are NJ-specific.
    referrer_data = {
        **ConfigurationData.referrer_data,
        # Omits the Immediate Help tab from the results page, matching the other recently
        # added states (MO, WA).
        "uiOptions": {"default": ["no_results_more_help"]},
        "shareLink": {"default": "https://screener.myfriendben.org/nj/step-1"},
        "stateName": {"default": "New Jersey"},
    }
