[mypy]
# Disables specific checks globally (e.g., assignment type errors and untyped imports)
disable_error_code = import-untyped
plugins = mypy_django_plugin.main
follow_imports = silent
exclude=(?x)(_template\.py | pe_program_init\.py | pe_program_member\.py | pe_program_spm\.py | program_init\.py | urgent_need_init\.py | ^.*/tests/.*$)

[mypy.plugins.django-stubs]
django_settings_module = benefits.settings
