name: 'Run Heroku Database Migrations'
description: 'Runs Django database migrations and syncs feature flags on Heroku'

inputs:
  heroku-api-key:
    description: 'Heroku API key'
    required: true
  heroku-app-name:
    description: 'Heroku application name'
    required: true

outputs:
  migrations-output:
    description: 'Output from database migrations'
    value: ${{ steps.migrations.outputs.migrations_output }}

runs:
  using: 'composite'
  steps:
    - name: Run database migrations
      id: migrations
      shell: bash
      env:
        HEROKU_API_KEY: ${{ inputs.heroku-api-key }}
      run: |
        echo "Running migrations..."
        set +e
        OUTPUT=$(heroku run -a ${{ inputs.heroku-app-name }} "python manage.py migrate && python manage.py sync_feature_flags" 2>&1)
        STATUS=$?
        set -e
        echo "$OUTPUT"
        DELIMITER="EOF_$(date +%s)"
        echo "migrations_output<<${DELIMITER}" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "${DELIMITER}" >> $GITHUB_OUTPUT

        if [ $STATUS -ne 0 ] && echo "$OUTPUT" | grep -q "Conflicting migrations detected"; then
          echo "Migration conflict detected. Auto-merge on Heroku is not supported (slug is read-only)."
          echo "Please resolve the conflict locally (python manage.py makemigrations --merge), commit, and re-deploy."
          exit 1
        elif [ $STATUS -ne 0 ]; then
          exit $STATUS
        fi
