name: 'Setup Python and Django Dependencies'
description: 'Sets up Python environment and installs Django project dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: requirements.txt

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
