# Generated by Django 4.2.22 on 2025-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screener",
            "0114_screen_utm_campaign_screen_utm_content_screen_utm_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_il_ctc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_il_eitc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
