# Generated by Django 4.2.22 on 2025-09-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0115_add_il_eitc_and_ctc_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_il_transit_reduced_fare",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
