# Generated by Django 4.2.22 on 2025-09-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0116_add_il_transit_reduced_fare_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_il_bap",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
