# Generated by Django 4.2.22 on 2025-09-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0117_add_has_il_bap_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="needs_savings",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
