# Generated by Django 4.2.22 on 2025-10-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0118_add_needs_savings_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_il_liheap",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
