# Generated by Django 4.2.22 on 2025-10-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0119_add_has_il_liheap_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_project_cope",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
