# Generated by Django 4.2.22 on 2025-11-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0120_screen_has_project_cope"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screen",
            old_name="needs_savings",
            new_name="needs_college_savings",
        ),
    ]
