# Generated by Django 4.2.22 on 2025-11-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0120_screen_has_project_cope"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_cesn_heap",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
