# Generated by Django 4.2.22 on 2025-11-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0121_screen_has_heap"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_nc_medicare_savings",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
