# Generated by Django 4.2.22 on 2025-11-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0121_screen_has_ma_heap"),
        ("screener", "0122_screen_has_nc_medicare_savings"),
    ]

    operations = []
