# Generated by Django 4.2.22 on 2025-11-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0123_merge_20251110_2243"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomestream",
            name="category",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
