# Generated by Django 4.2.22 on 2025-12-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0124_add_income_stream_category"),
        ("screener", "0124_rename_needs_savings_to_needs_college_savings"),
    ]

    operations = []
