# Generated by Django 4.2.22 on 2025-12-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0124_rename_needs_savings_to_needs_college_savings"),
    ]

    operations = [
        migrations.AddField(
            model_name="householdmember",
            name="is_care_worker",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
