# Generated by Django 4.2.22 on 2025-12-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0124_rename_needs_savings_to_needs_college_savings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screen",
            old_name="has_cccap",
            new_name="has_ccap",
        ),
    ]
