# Generated by Django 4.2.22 on 2025-12-09 16:25

from django.db import migrations, models


def backfill_income_categories(apps, schema_editor):
    """
    Backfill the category field for existing IncomeStream records based on income type.
    Maps income types to their categories according to the income_options structure in base.py.
    """
    IncomeStream = apps.get_model("screener", "IncomeStream")

    # Category mapping based on income_options structure in configuration/white_labels/base.py
    # Includes state-specific income types from TX, MA, and IL
    INCOME_TYPE_TO_CATEGORY = {
        # Employment income types
        "wages": "employment",
        "selfEmployment": "employment",
        # Government benefit types
        "sSDisability": "government",
        "sSRetirement": "government",
        "sSI": "government",
        "sSSurvivor": "government",
        "sSDependent": "government",
        "unemployment": "government",
        "cashAssistance": "government",
        "cOSDisability": "government",
        "workersComp": "government",
        "veteran": "government",
        # State-specific disability income types
        "StateDisability": "government",  # TX
        "stateDisability": "government",  # MA
        "iLStateDisability": "government",  # IL
        # Support and gifts
        "childSupport": "support",
        "alimony": "support",
        "gifts": "support",
        "boarder": "support",
        # Investment and retirement
        "pension": "investment",
        "investment": "investment",
        "rental": "investment",
        "deferredComp": "investment",
    }

    # Update each income stream with its category
    updated_count = 0
    for income_stream in IncomeStream.objects.all():
        if income_stream.type in INCOME_TYPE_TO_CATEGORY:
            income_stream.category = INCOME_TYPE_TO_CATEGORY[income_stream.type]
            income_stream.save(update_fields=["category"])
            updated_count += 1

    print(f"Backfilled {updated_count} IncomeStream records with categories")


def reverse_backfill(apps, schema_editor):
    """
    Reverse the backfill by setting all categories to None.
    """
    IncomeStream = apps.get_model("screener", "IncomeStream")
    IncomeStream.objects.all().update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0125_rename_has_cccap_screen_has_ccap"),
    ]

    operations = [
        # Step 1: Add the category field as nullable
        migrations.AddField(
            model_name="incomestream",
            name="category",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        # Step 2: Backfill existing records with categories
        migrations.RunPython(backfill_income_categories, reverse_backfill),
    ]
