# Generated by Django 4.2.22 on 2025-12-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0125_rename_has_cccap_screen_has_ccap"),
        ("screener", "0125_screen_has_nc_head_start"),
    ]

    operations = []
