# Generated by Django 4.2.22 on 2025-12-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0125_screen_has_head_start"),
        ("screener", "0126_add_income_category_with_backfill"),
    ]

    operations = []
