# Generated by Django 4.2.22 on 2025-12-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0126_add_income_category_with_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_nc_head_start",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
