# Generated by Django 4.2.22 on 2025-12-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0126_screen_has_early_head_start"),
        ("screener", "0127_merge_20251209_2117"),
    ]

    operations = []
