# Generated by Django 4.2.22 on 2025-12-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0128_merge_20251209_2204"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_nc_head_start",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
