# Generated by Django 4.2.22 on 2025-12-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0128_merge_20251209_2204"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_il_hbwd",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
