# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0129_add_has_ma_homebridge"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_ma_dhsp_afterschool",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
