# Generated by Django 4.2.22 on 2025-12-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0130_add_has_ma_dhsp_afterschool"),
        ("screener", "0130_add_has_ma_door_to_door"),
    ]

    operations = []
