# Generated by Django 4.2.22 on 2025-12-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0125_householdmember_is_care_worker"),
        ("screener", "0131_merge_20251218_2016"),
    ]

    operations = []
