# Generated by Django 4.2.22 on 2026-01-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0132_merge_20251223_1725"),
        ("screener", "0132_screen_has_il_hbwd"),
    ]

    operations = []
