# Generated by Django 4.2.22 on 2026-01-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0133_merge_20260106_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programeligibilitysnapshot",
            name="name_abbreviated",
            field=models.CharField(max_length=120),
        ),
    ]
