# Generated by Django 4.2.22 on 2026-01-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0125_add_has_harris_county_rides"),
        ("screener", "0134_increase_name_abbreviated_length"),
    ]

    operations = []
