# Generated by Django 4.2.22 on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0134_increase_name_abbreviated_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_ccs",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
