# Generated by Django 4.2.22 on 2026-01-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0135_add_has_dart"),
        ("screener", "0135_merge_20260111_2031"),
    ]

    operations = []
