# Generated by Django 4.2.22 on 2026-01-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0135_screen_has_ccs"),
        ("screener", "0136_merge_20260113"),
    ]

    operations = []
