# Generated by Django 4.2.22 on 2026-01-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0137_merge_0135_screen_has_ccs_0136_merge_20260113"),
    ]

    operations = [
        migrations.AddField(
            model_name="householdmember",
            name="student_has_work_study",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="student_job_training_program",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="student_works_20_plus_hrs",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
