# Generated by Django 4.2.22 on 2026-01-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0137_merge_0135_screen_has_ccs_0136_merge_20260113"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelabel",
            name="feature_flags",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
