# Generated by Django 4.2.22 on 2026-01-29 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0137_merge_0135_screen_has_ccs_0136_merge_20260113"),
    ]

    operations = [
        migrations.CreateModel(
            name="NPSScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        choices=[("floating", "Floating Widget"), ("inline", "Inline Section")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("score_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eligibility_snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nps_score",
                        to="screener.eligibilitysnapshot",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="npsscore",
            constraint=models.CheckConstraint(
                check=models.Q(("score__gte", 0), ("score__lte", 10)), name="nps_score_range"
            ),
        ),
    ]
