# Generated by Django 4.2.22 on 2026-01-28 03:44

from django.db import migrations


def rename_white_label(apps, schema_editor):
    WhiteLabel = apps.get_model("screener", "WhiteLabel")
    WhiteLabel.objects.filter(code="co_energy_calculator").update(code="cesn")


def reverse_rename_white_label(apps, schema_editor):
    WhiteLabel = apps.get_model("screener", "WhiteLabel")
    WhiteLabel.objects.filter(code="cesn").update(code="co_energy_calculator")


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0137_merge_0135_screen_has_ccs_0136_merge_20260113"),
    ]

    operations = [
        migrations.RunPython(rename_white_label, reverse_rename_white_label),
    ]
