# Generated by Django 4.2.22 on 2026-02-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0138_add_features_to_whitelabel"),
        ("screener", "0138_rename_co_energy_calculator_to_cesn"),
    ]

    operations = []
