# Generated by Django 4.2.22 on 2026-01-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0138_npsscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="npsscore",
            name="variant",
            field=models.CharField(
                blank=True,
                choices=[("floating", "Floating Widget"), ("inline", "Inline Section")],
                max_length=20,
                null=True,
            ),
        ),
    ]
