# Generated by Django 4.2.22 on 2026-02-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0138_add_features_to_whitelabel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlags",
            fields=[],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("screener.whitelabel",),
        ),
    ]
