# Generated by Django 4.2.22 on 2026-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0140_rename_co_energy_calculator_to_cesn"),
    ]

    operations = [
        migrations.AddField(
            model_name="householdmember",
            name="student_has_work_study",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="student_job_training_program",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="student_works_20_plus_hrs",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
