# Generated by Django 4.2.22 on 2026-02-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0139_merge_0138_add_features_to_whitelabel_0138_npsscore"),
        ("screener", "0141_householdmember_student_has_work_study_and_more"),
    ]

    operations = []
