# Generated by Django 4.2.22 on 2026-02-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0142_merge_20260217_1810"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_ma_cpp",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
