# Generated by Django 4.2.22 on 2026-02-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0143_screen_has_ma_cpp"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_ma_taxi_discount",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
