# Generated by Django 4.2.22 on 2026-02-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0144_add_has_ma_taxi_discount"),
        ("screener", "0144_screen_has_ma_cmsp"),
    ]

    operations = []
