# Generated by Django 4.2.22 on 2026-02-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0145_merge_20260224_1703"),
        ("screener", "0145_merge_20260224_1800"),
    ]

    operations = []
