# Generated by Django 4.2.22 on 2026-03-30 20:22

from django.db import migrations


def backfill_has_head_start(apps, schema_editor):
    Screen = apps.get_model("screener", "Screen")
    Screen.objects.filter(has_chs=True, has_head_start=False).update(has_head_start=True)


def reverse_backfill_has_head_start(apps, schema_editor):
    pass  # irreversible — cannot distinguish original has_head_start=True from backfilled values


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0148_add_currentbenefit"),
    ]

    operations = [
        migrations.RunPython(backfill_has_head_start, reverse_backfill_has_head_start),
        migrations.RemoveField(
            model_name="screen",
            name="has_chs",
        ),
    ]
