# Generated by Django 4.2.22 on 2026-03-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0148_backfill_has_head_start_from_has_chs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screen",
            name="has_chs",
        ),
    ]
