# Generated by Django 4.2.22 on 2026-05-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0152_backfill_snapshot_value_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="needs_disability_resources",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
