# Generated by Django 4.2.28 on 2026-05-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0152_backfill_snapshot_value_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_udp",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
