# Generated by Django 4.2.28 on 2026-06-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0153_add_needs_disability_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_wa_wap",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
