# Generated by Django 4.2.28 on 2026-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0155_add_has_wa_wap_to_screen"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="needs_aging_resources",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
