# Generated by Django 4.2.28 on 2026-07-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0157_drop_has_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='has_gig_income',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='has_other_income',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='is_employed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
