# Generated by Django 4.2.28 on 2026-07-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0157_drop_has_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="needs_homeless_services",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="needs_free_low_cost_medical_care",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
