# Generated by Django 4.2.22 on 2026-06-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0157_drop_has_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programeligibilitysnapshot",
            name="value_type",
        ),
    ]
