# Generated by Django 4.2.28 on 2026-08-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0159_screen_needs_homeless_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='needs_transportation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
