# Generated by Django 4.2.28 on 2026-08-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0160_screen_needs_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='needs_medical_expenses_and_debt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
