# Generated by Django 4.2.28 on 2026-09-01 17:19
#
# Benbot (Benji) conversation state. Django owns this schema; mfb-ai-service is the
# writer at runtime (see the AssistantConversation docstring in screener/models.py).
# Inert until ai-service is pointed at this database, so it is safe to ship alone.

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0161_screen_needs_medical_expenses_and_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('conversation_id', models.UUIDField(primary_key=True, serialize=False)),
                ('screen_uuid', models.UUIDField(db_index=True)),
                ('white_label', models.CharField(blank=True, max_length=32, null=True)),
                ('locale', models.CharField(blank=True, max_length=12, null=True)),
                ('mode', models.CharField(blank=True, max_length=16, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('message_id', models.UUIDField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('role', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('client_message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('suggested_actions', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='screener.assistantconversation')),
            ],
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['updated_at'], name='assistant_conv_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('screen_uuid',), name='assistant_one_active_conv_per_screen'),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='assistant_msg_seq_unique'),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('conversation', 'client_message_id'), name='assistant_msg_client_id_unique'),
        ),
    ]
