# Make the AssistantMessage -> AssistantConversation foreign key cascade in the
# DATABASE, not only in the ORM.
#
# Django never emits ON DELETE CASCADE; `on_delete=models.CASCADE` is emulated in
# Python by the ORM's collector. That is not enough for these two tables:
#
#   - mfb-ai-service is a writer on these tables (Django owns the schema, ai-service
#     owns the runtime — see screener/models.AssistantConversation) and has no ORM,
#     so anything it deletes goes out as raw SQL.
#   - Conversation history is retained indefinitely by decision, but an individual
#     deletion request would be served by a bulk DELETE. With the cascade in place
#     that is one statement; without it, it is a fetch-every-child-PK-into-memory
#     ORM traversal, or a foreign-key violation.
#
# Without a database-level cascade both paths fail on a foreign-key violation.
#
# This is a separate migration from 0162 on purpose: Django collects CreateModel's
# foreign-key constraints into the schema editor's `deferred_sql` and flushes them
# when the editor exits, which is AFTER every operation in that migration. A lookup
# in 0162 therefore finds no constraint to alter.

from django.db import migrations

# The constraint name is generated by Django and carries a hash, so it has to be
# looked up rather than hardcoded. DEFERRABLE INITIALLY DEFERRED is preserved in both
# directions so the constraint keeps behaving exactly as Django's own foreign keys do
# for ORM writes.
_LOOKUP_AND_REPLACE = """
DO $$
DECLARE
    fk_name text;
BEGIN
    SELECT conname INTO STRICT fk_name
    FROM pg_constraint
    WHERE conrelid = 'screener_assistantmessage'::regclass
      AND contype = 'f';

    EXECUTE format('ALTER TABLE screener_assistantmessage DROP CONSTRAINT %I', fk_name);
    EXECUTE format(
        'ALTER TABLE screener_assistantmessage ADD CONSTRAINT %I '
        'FOREIGN KEY (conversation_id) '
        'REFERENCES screener_assistantconversation(conversation_id) '
        '%s DEFERRABLE INITIALLY DEFERRED',
        fk_name,
        '{on_delete}'
    );
END $$;
"""

# INTO STRICT so a missing (or ambiguous) constraint raises instead of passing NULL
# to format() with a confusing "null values cannot be formatted as an SQL identifier".
_ADD_DB_CASCADE = _LOOKUP_AND_REPLACE.format(on_delete="ON DELETE CASCADE")
_DROP_DB_CASCADE = _LOOKUP_AND_REPLACE.format(on_delete="")


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0162_assistant_conversation_state"),
    ]

    operations = [
        migrations.RunSQL(
            sql=_ADD_DB_CASCADE,
            reverse_sql=_DROP_DB_CASCADE,
        ),
    ]
