# Generated by Django 4.2.28 on 2026-09-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0163_assistant_message_db_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='was_in_foster_care',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
