# Generated by Django 4.2.28 on 2026-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0164_householdmember_was_in_foster_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitysnapshot',
            name='dropped_programs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
