# Generated by Django 4.2.28 on 2026-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0164_householdmember_was_in_foster_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Thumbs up'), (-1, 'Thumbs down')], null=True),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.CheckConstraint(check=models.Q(('rating__isnull', True), ('rating__in', (1, -1)), _connector='OR'), name='assistant_msg_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.CheckConstraint(check=models.Q(('rating__isnull', True), ('role', 'assistant'), _connector='OR'), name='assistant_msg_rating_assistant_only'),
        ),
    ]
