# Generated by Django 4.2.28 on 2026-09-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0165_assistant_message_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='rating_reason',
            field=models.CharField(blank=True, choices=[('inaccurate', "This isn't right"), ('not_my_results', "This isn't about my results"), ('bad_link', "A link or phone number didn't work"), ('unanswered', "It didn't answer what I asked"), ('hard_to_follow', 'Hard to follow, or too long'), ('wrong_tone', 'It felt wrong for my situation'), ('other', 'Something else')], max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.CheckConstraint(check=models.Q(('rating_reason__isnull', True), ('rating', -1), _connector='OR'), name='assistant_msg_reason_needs_thumbs_down'),
        ),
    ]
