# Generated by Django 4.2.28 on 2026-09-23 18:37

from django.db import migrations, models


# WHY THIS USES A PLAIN AddConstraint, not AddConstraintNotValid + ValidateConstraint.
#
# `AddConstraint` validates existing rows under an ACCESS EXCLUSIVE lock, which on a
# large table blocks reads and writes for the length of the scan. Staging the
# validation is the right answer when there is anything to scan. Measured on
# 2026-09-23, there is not:
#
#     production  (cobenefits-api)          0 rows   — `benbot` is false on all 11
#                                                      white labels, so Benji has
#                                                      never stored a turn there
#     staging     (cobenefits-api-staging)  232 rows (16 conversations)
#
# A NOT VALID constraint plus a second non-atomic migration to validate it would buy
# nothing against an empty table and cost a permanently more confusing migration
# history. Re-measure before adding a constraint to this table once Benji is actually
# live in production — this reasoning expires the moment the flag is flipped.


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0165_assistant_message_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='rating_reason',
            field=models.CharField(blank=True, choices=[('inaccurate', 'Not accurate'), ('not_my_results', 'Not about my results'), ('unanswered', "Didn't answer me"), ('hard_to_follow', 'Confusing or too long'), ('other', 'Something else')], max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.CheckConstraint(check=models.Q(('rating_reason__isnull', True), models.Q(('rating__isnull', False), ('rating', -1)), _connector='OR'), name='assistant_msg_reason_needs_thumbs_down'),
        ),
    ]
