# Generated by Django 4.2.28 on 2026-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0166_assistant_message_rating_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitysnapshot',
            name='dropped_programs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
