# Generated by Django 4.2.28 on 2026-09-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0167_eligibilitysnapshot_dropped_programs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='householdmember',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='incomestream',
            options={'ordering': ['id']},
        ),
    ]
