# Generated by Django 4.2.22 on 2025-11-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0002_alter_validation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="validation",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
