# Generated by Django 4.2.22 on 2026-02-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0003_validation_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="validation",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="validation",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
