# Generated by Django 4.2.22 on 2025-08-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0116_update_category_icon_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="excludes_programs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Programs that are excluded when eligible for this program.",
                related_name="excluded_by_programs",
                to="programs.program",
            ),
        ),
    ]
