# Generated by Django 4.2.22 on 2025-09-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0117_add_excludes_programs"),
        ("programs", "0117_program_navigators"),
    ]

    operations = []
