# Generated by Django 4.2.22 on 2025-09-11 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0006_move_zh_data"),
        ("programs", "0117_add_excludes_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="urgentneed",
            name="notification_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="urgent_need_notification_message",
                to="translations.translation",
            ),
        ),
    ]
