# Generated by Django 4.2.22 on 2025-09-15
import uuid
from django.db import migrations


def add_notification_message_translations(apps, schema_editor):
    """
    Creates Translation objects for notification_message field for all existing UrgentNeed records.
    """
    UrgentNeed = apps.get_model("programs", "UrgentNeed")
    Translation = apps.get_model("translations", "Translation")

    for urgent_need in UrgentNeed.objects.all():
        # Only create if notification_message doesn't already exist (idempotency)
        if urgent_need.notification_message_id is None:
            # Generate label following the pattern from UrgentNeedManager
            # Use external_name if available, otherwise use uuid
            identifier = urgent_need.external_name if urgent_need.external_name else str(uuid.uuid4())
            label = f"urgent_need.{identifier}_{urgent_need.id}-notification_message"

            # Create translation with empty string
            translation = Translation.objects.add_translation(label=label, default_message="", no_auto=False)

            # Update the urgent_need with the new translation
            UrgentNeed.objects.filter(pk=urgent_need.id).update(notification_message=translation.id)


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0118_add_notification_message_nullable"),
    ]

    operations = [migrations.RunPython(add_notification_message_translations, migrations.RunPython.noop)]
