# Generated by Django 4.2.22 on 2025-09-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0118_add_notification_message_nullable"),
        ("programs", "0119_urgent_need_notification_message_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urgentneed",
            name="notification_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="urgent_need_notification_message",
                to="translations.translation",
            ),
        ),
    ]
