# Generated by Django 4.2.22 on 2025-09-16 22:46

from django.db import migrations


def add_savings_icon(apps, schema_editor):
    CategoryIconName = apps.get_model("programs", "CategoryIconName")
    CategoryIconName.objects.get_or_create(name="savings")


def remove_savings_icon(apps, schema_editor):
    CategoryIconName = apps.get_model("programs", "CategoryIconName")
    CategoryIconName.objects.filter(name="savings").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0120_urgent_need_notification_message_required"),
    ]

    operations = [
        migrations.RunPython(add_savings_icon, remove_savings_icon),
    ]
