# Generated by Django 4.2.22 on 2025-09-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0121_add_savings_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="show_on_current_benefits",
            field=models.BooleanField(
                default=True,
                help_text="Display this program on the current benefits page",
            ),
        ),
        migrations.AddField(
            model_name="urgentneed",
            name="show_on_current_benefits",
            field=models.BooleanField(
                default=True,
                help_text="Display this urgent need on the current benefits page",
            ),
        ),
    ]
