# Generated by Django 4.2.22 on 2025-09-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0118_add_needs_savings_field"),
        ("programs", "0122_program_show_on_current_benefits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramDurationMultiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average_duration_months",
                    models.FloatField(help_text="Average duration in months based on research data"),
                ),
                (
                    "confidence_range_lower",
                    models.FloatField(help_text="Lower bound multiplier for confidence range (e.g., 0.67 for -33%)"),
                ),
                (
                    "confidence_range_upper",
                    models.FloatField(help_text="Upper bound multiplier for confidence range (e.g., 1.33 for +33%)"),
                ),
                (
                    "data_source",
                    models.CharField(
                        help_text="Source of the duration data (e.g., 'USDA 2024 SNAP Report')",
                        max_length=256,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the data source or methodology",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duration_multipliers",
                        to="programs.program",
                    ),
                ),
                (
                    "white_label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_duration_multipliers",
                        to="screener.whitelabel",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["program", "white_label"],
                        name="programs_pr_program_2f1e27_idx",
                    )
                ],
                "unique_together": {("program", "white_label")},
            },
        ),
        migrations.CreateModel(
            name="LifetimeValuePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "predicted_duration_months",
                    models.FloatField(help_text="Predicted duration in months based on multiplier calculation"),
                ),
                (
                    "confidence_interval_lower",
                    models.FloatField(help_text="Lower bound of duration confidence interval in months"),
                ),
                (
                    "confidence_interval_upper",
                    models.FloatField(help_text="Upper bound of duration confidence interval in months"),
                ),
                (
                    "estimated_lifetime_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated total lifetime benefit value in dollars",
                        max_digits=10,
                    ),
                ),
                (
                    "explanation_text",
                    models.TextField(help_text="User-friendly explanation of the lifetime projection"),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Risk factors that might affect the duration",
                    ),
                ),
                (
                    "multiplier_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version of the multiplier calculation used",
                        max_length=32,
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        default="simple_multiplier",
                        help_text="Method used for calculation (e.g., 'simple_multiplier', 'ml_model')",
                        max_length=64,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifetime_predictions",
                        to="programs.program",
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifetime_predictions",
                        to="screener.screen",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["screen", "program"],
                        name="programs_li_screen__a233d8_idx",
                    ),
                    models.Index(
                        fields=["prediction_date"],
                        name="programs_li_predict_9287c1_idx",
                    ),
                ],
            },
        ),
    ]
