# Generated by Django 4.2.22 on 2025-10-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0122_program_show_on_current_benefits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name_plural": "Expense Types",
            },
        ),
        migrations.AddField(
            model_name="urgentneed",
            name="required_expense_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="If empty, urgent need shown to all users. If selected, user must have at least one of these expense types.",
                related_name="urgent_needs",
                to="programs.expensetype",
            ),
        ),
    ]
