# Generated by Django 4.2.22 on 2025-10-21 16:55

from django.db import migrations


def populate_expense_types(apps, schema_editor):
    """
    Populate ExpenseType table with expense options from configuration.
    Matches keys from configuration/white_labels/base.py expense_options (lines 348-366)
    """
    ExpenseType = apps.get_model("programs", "ExpenseType")

    # These MUST match keys from configuration/white_labels/base.py expense_options
    expense_types = [
        "rent",
        "telephone",
        "internet",
        "otherUtilities",
        "heating",
        "mortgage",
        "propertyTax",
        "hoa",
        "homeownersInsurance",
        "medical",
        "cooling",
        "childCare",
        "childSupport",
        "dependentCare",
    ]

    for exp_type in expense_types:
        ExpenseType.objects.get_or_create(name=exp_type)


def reverse_populate(apps, schema_editor):
    """Allow migration to be reversed safely"""
    ExpenseType = apps.get_model("programs", "ExpenseType")
    ExpenseType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0123_add_expensetype_urgentneed_required_expense_types"),
    ]

    operations = [
        migrations.RunPython(populate_expense_types, reverse_populate),
    ]
