# Generated by Django 4.2.22 on 2025-10-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0124_populate_expense_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="value_format",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Default (Monthly)"),
                    ("lump_sum", "Lump Sum (One-time payment)"),
                    ("estimated_annual", "Estimated Annual (Average annual savings)"),
                ],
                help_text="Configure how the program value is displayed to users.",
                max_length=120,
                null=True,
            ),
        ),
    ]
