# Generated by Django 4.2.22 on 2025-11-13

from django.db import migrations, models
import django.db.models.deletion


def populate_navigator_ordering(apps, schema_editor):
    """
    Copy existing Program-Navigator relationships to new through table.
    Assigns default order=999 to preserve current behavior (items at end).
    """
    with schema_editor.connection.cursor() as cursor:
        # Copy all existing relationships to new through table
        # No ON CONFLICT needed - old M2M table already has unique constraint
        cursor.execute("""
            INSERT INTO programs_program_navigators_ordered 
                (program_id, navigator_id, "order")
            SELECT 
                program_id, 
                navigator_id, 
                999
            FROM programs_navigator_programs
        """)
        
        rows_copied = cursor.rowcount
        if rows_copied > 0:
            print(f"✓ Copied {rows_copied} navigator relationships with default ordering")


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear the through table"""
    ProgramNavigator = apps.get_model("programs", "ProgramNavigator")
    ProgramNavigator.objects.all().delete()


class Migration(migrations.Migration):
    """
    Adds navigator ordering functionality using a through table.
    
    This migration:
    1. Creates ProgramNavigator through model with order field
    2. Adds programs_ordered M2M field to Navigator
    3. Keeps existing programs field for backward compatibility
    4. Copies all existing relationships to new table
    
    Both relationships remain active - this is the EXPAND phase.
    Future migration will remove old field (CONTRACT phase).
    """

    dependencies = [
        ("programs", "0125_alter_program_value_format"),
    ]

    operations = [
        # Step 1: Create ProgramNavigator through model
        migrations.CreateModel(
            name="ProgramNavigator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=999,
                        help_text="Lower values appear first. Drag to reorder in admin.",
                    ),
                ),
                (
                    "navigator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_navigators",
                        to="programs.navigator",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_navigators",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Navigator",
                "verbose_name_plural": "Program Navigators",
                "db_table": "programs_program_navigators_ordered",
                "ordering": ["order", "id"],
                "unique_together": {("program", "navigator")},
            },
        ),
        
        # Step 2: Make existing programs field explicit (backward compatibility)
        migrations.AlterField(
            model_name="navigator",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                db_table="programs_navigator_programs",
                related_name="navigator",
                to="programs.program",
            ),
        ),
        
        # Step 3: Add new programs_ordered field with through table
        migrations.AddField(
            model_name="navigator",
            name="programs_ordered",
            field=models.ManyToManyField(
                blank=True,
                related_name="navigators_ordered",
                through="programs.ProgramNavigator",
                to="programs.program",
            ),
        ),
        
        # Step 4: Copy existing data to new through table
        migrations.RunPython(
            populate_navigator_ordering,
            reverse_code=reverse_populate,
        ),
    ]
