# Generated by Django 4.2.22 on 2025-11-13
#
# ⚠️ CONTRACT PHASE - Only run after validation period
#
# Deploy this migration ONLY after:
# - Migration 0126 has been stable in production for 1+ week
# - Navigator ordering functionality fully validated
# - No rollback anticipated
# - Team approval obtained

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Finalizes navigator ordering by removing old field and cleaning up.

    This migration:
    1. Removes old 'programs' M2M field
    2. Renames 'programs_ordered' to 'programs' (restores original name)
    3. Drops old M2M table

    This completes the CONTRACT phase of expand/contract pattern.
    Run only after thorough validation of 0126 in production.
    """

    dependencies = [
        ("programs", "0126_add_navigator_ordering"),
    ]

    operations = [
        # Step 1: Remove old programs M2M field
        migrations.RemoveField(
            model_name="navigator",
            name="programs",
        ),
        # Step 2: Rename programs_ordered to programs (restore original API)
        migrations.RenameField(
            model_name="navigator",
            old_name="programs_ordered",
            new_name="programs",
        ),
        # Step 3: Update field definition with correct related_name
        migrations.AlterField(
            model_name="navigator",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                related_name="navigator",
                through="programs.ProgramNavigator",
                to="programs.program",
            ),
        ),
        # Step 4: Drop old M2M table
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS programs_navigator_programs CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
