# Generated by Django 4.2.22 on 2025-12-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0129_update_legal_status_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="legal_status_required",
            field=models.ManyToManyField(
                blank=True,
                help_text="User must match at least one of the selected statuses to be eligible for this program.",
                related_name="programs",
                to="programs.legalstatus",
                verbose_name="Legal status required",
            ),
        ),
    ]
