# Generated by Django 4.2.22 on 2026-01-28 03:53

from django.db import migrations


def rename_co_energy_calculator_to_cesn(apps, _schema_editor):
    Program = apps.get_model("programs", "Program")
    ProgramCategory = apps.get_model("programs", "ProgramCategory")
    WarningMessage = apps.get_model("programs", "WarningMessage")
    TranslationOverride = apps.get_model("programs", "TranslationOverride")

    # Update all programs with co_energy_calculator_ prefix to cesn_
    # Using raw SQL via update() to avoid parler translation issues with historical models
    from django.db.models.functions import Replace
    from django.db.models import Value, F

    Program.objects.filter(name_abbreviated__startswith="co_energy_calculator_").update(
        name_abbreviated=Replace(F("name_abbreviated"), Value("co_energy_calculator_"), Value("cesn_"))
    )

    # Update all program categories with co_energy_calculator_ prefix to cesn_
    ProgramCategory.objects.filter(external_name__startswith="co_energy_calculator_").update(
        external_name=Replace(F("external_name"), Value("co_energy_calculator_"), Value("cesn_"))
    )

    # Update all warning messages with co_energy_calculator calculator to cesn
    WarningMessage.objects.filter(calculator__startswith="co_energy_calculator").update(
        calculator=Replace(F("calculator"), Value("co_energy_calculator"), Value("cesn"))
    )

    # Update all translation overrides with co_energy_calculator calculator to cesn
    TranslationOverride.objects.filter(calculator__startswith="co_energy_calculator").update(
        calculator=Replace(F("calculator"), Value("co_energy_calculator"), Value("cesn"))
    )


def reverse_rename_cesn_to_co_energy_calculator(apps, _schema_editor):
    Program = apps.get_model("programs", "Program")
    ProgramCategory = apps.get_model("programs", "ProgramCategory")
    WarningMessage = apps.get_model("programs", "WarningMessage")
    TranslationOverride = apps.get_model("programs", "TranslationOverride")

    from django.db.models.functions import Replace
    from django.db.models import Value, F

    # Reverse: update all programs with cesn_ prefix back to co_energy_calculator_
    Program.objects.filter(name_abbreviated__startswith="cesn_").update(
        name_abbreviated=Replace(F("name_abbreviated"), Value("cesn_"), Value("co_energy_calculator_"))
    )

    # Reverse: update all program categories with cesn_ prefix back to co_energy_calculator_
    ProgramCategory.objects.filter(external_name__startswith="cesn_").update(
        external_name=Replace(F("external_name"), Value("cesn_"), Value("co_energy_calculator_"))
    )

    # Reverse: update all warning messages with cesn calculator back to co_energy_calculator
    WarningMessage.objects.filter(calculator__startswith="cesn_").update(
        calculator=Replace(F("calculator"), Value("cesn_"), Value("co_energy_calculator_"))
    )

    # Reverse: update all translation overrides with cesn calculator back to co_energy_calculator
    TranslationOverride.objects.filter(calculator__startswith="cesn_").update(
        calculator=Replace(F("calculator"), Value("cesn_"), Value("co_energy_calculator_"))
    )


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0130_alter_program_legal_status_required"),
    ]

    operations = [
        migrations.RunPython(rename_co_energy_calculator_to_cesn, reverse_rename_cesn_to_co_energy_calculator),
    ]
