# Generated by Django 4.2.22 on 2026-02-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0130_alter_program_legal_status_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="county",
            options={"verbose_name_plural": "Counties"},
        ),
        migrations.AlterModelOptions(
            name="programcategory",
            options={"verbose_name_plural": "Program categories"},
        ),
    ]
