# Generated by Django 4.2.22 on 2026-01-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0130_alter_program_legal_status_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramConfigImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "filename",
                    models.CharField(
                        help_text="Name of the JSON configuration file (without path)", max_length=255, unique=True
                    ),
                ),
                (
                    "program_name",
                    models.CharField(help_text="The name_abbreviated of the program that was created", max_length=255),
                ),
                (
                    "white_label_code",
                    models.CharField(help_text="The white label code for this program", max_length=64),
                ),
                (
                    "imported_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this configuration was imported"),
                ),
            ],
            options={
                "verbose_name": "Program Config Import",
                "verbose_name_plural": "Program Config Imports",
                "ordering": ["-imported_at"],
            },
        ),
    ]
