# Generated by Django 4.2.22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0131_add_program_config_import"),
        ("programs", "0132_rename_cesn_program_abbreviations"),
    ]

    operations = []
