# Generated by Django 4.2.22 on 2026-03-30 20:18

from django.db import migrations


def rename_chs_to_co_head_start(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    Program.objects.filter(name_abbreviated="chs").update(name_abbreviated="co_head_start", external_name="co_head_start")


def rename_co_head_start_to_chs(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    Program.objects.filter(name_abbreviated="co_head_start").update(name_abbreviated="chs", external_name="chs")


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0134_program_show_in_has_benefits_step"),
    ]

    operations = [
        migrations.RunPython(rename_chs_to_co_head_start, rename_co_head_start_to_chs),
    ]
