# Generated by Django 4.2.22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0135_rename_chs_to_co_head_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="has_calculator",
            field=models.BooleanField(default=True, help_text="Whether this program has an eligibility calculator"),
        ),
        migrations.AddField(
            model_name="program",
            name="base_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("snap", "SNAP"),
                    ("tanf", "TANF"),
                    ("wic", "WIC"),
                    ("ssi", "SSI"),
                    ("ssdi", "SSDI"),
                    ("medicaid", "Medicaid"),
                    ("aca", "ACA"),
                    ("eitc", "EITC"),
                    ("ctc", "CTC"),
                    ("nslp", "NSLP"),
                    ("nfp", "NFP"),
                    ("head_start", "Head Start"),
                    ("early_head_start", "Early Head Start"),
                    ("section_8", "Section 8"),
                    ("csfp", "CSFP"),
                    ("lifeline", "Lifeline"),
                    ("chp", "CHP"),
                    ("oap", "OAP"),
                    ("liheap", "LIHEAP"),
                    ("wap", "WAP"),
                    ("medicare_savings", "Medicare Savings"),
                    ("ccap", "CCAP"),
                ],
                help_text="Cross-white-label program grouping for analytics (e.g. co_snap, il_snap → snap)",
                max_length=32,
                null=True,
            ),
        ),
    ]
