# Generated by Django 4.2.22

from django.db import migrations

# Programs to create as tracking-only (has_calculator=False, show_in_has_benefits_step=True).
# These are generic/cross-WL programs that exist in the category_benefits config for a white label
# but don't have a Program record scoped to that WL. They allow the CurrentBenefit join table
# to track what benefits a user already has even when there's no eligibility calculator.
#
# name/description text is taken from the respective white label's category_benefits config.
TRACKING_PROGRAMS = [
    # CESN (WL code: cesn) — config uses generic keys like "snap", "tanf", etc.
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_snap",
        "name_text": "Supplemental Nutrition Assistance Program (SNAP): ",
        "description_text": "Food assistance",
        "base_program": "snap",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_tanf",
        "name_text": "Temporary Assistance for Needy Families/Colorado Works (TANF): ",
        "description_text": "Cash assistance and work support",
        "base_program": "tanf",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_wic",
        "name_text": "Special Supplemental Nutrition Program for Women, Infants, and Children (WIC): ",
        "description_text": "Food and breastfeeding assistance",
        "base_program": "wic",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_ssi",
        "name_text": "Supplemental Security Income (SSI): ",
        "description_text": "Federal cash assistance for individuals who are disabled, blind, or 65 years of age or older",
        "base_program": "ssi",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_ssdi",
        "name_text": "Social Security Disability Insurance (SSDI): ",
        "description_text": "Social security benefit for people with disabilities",
        "base_program": "ssdi",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_chp",
        "name_text": "Child Health Plan Plus (CHP+): ",
        "description_text": "Low-cost health insurance for children and pregnant women",
        "base_program": "chp",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_oap",
        "name_text": "Old Age Pension (OAP): ",
        "description_text": "State cash assistance for individuals 60 years of age or older",
        "base_program": "oap",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_section_8",
        "name_text": "Housing Choice Voucher: ",
        "description_text": "Rent Subsidy (formerly Section 8)",
        "base_program": "section_8",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_rtdlive",
        "name_text": "RTD LiVE: ",
        "description_text": "Discounted RTD fares",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_andcs",
        "name_text": "Aid to the Needy Disabled - Colorado Supplement (AND-CS): ",
        "description_text": "State cash assistance for individuals who are disabled and receiving SSI",
    },
    {
        "white_label_code": "cesn",
        "name_abbreviated": "cesn_medicaid",
        "name_text": "Health First Colorado (Medicaid): ",
        "description_text": "Free / low-cost public health insurance",
        "base_program": "medicaid",
    },
    # NC (WL code: nc) — generic programs missing from NC's program table
    {
        "white_label_code": "nc",
        "name_abbreviated": "nc_leap",
        "name_text": "NC LIEAP (Low-Income Energy Assistance Program): ",
        "description_text": "Help with winter heating bills",
        "base_program": "liheap",
    },
    {
        "white_label_code": "nc",
        "name_abbreviated": "nc_cccap",
        "name_text": "NC Subsidized Child Care Assistance: ",
        "description_text": "Help with child care costs",
        "base_program": "ccap",
    },
]


def create_tracking_programs(apps, schema_editor):
    """
    Creates Program records for tracking-only programs (no calculator).
    Uses real model imports because Program.objects.new_program() handles the
    complex Translation FK creation that historical models can't support.
    """
    from programs.models import Program
    from screener.models import WhiteLabel
    from translations.models import Translation

    for p in TRACKING_PROGRAMS:
        # Skip if white label doesn't exist (e.g. in CI test databases)
        if not WhiteLabel.objects.filter(code=p["white_label_code"]).exists():
            continue

        existing = Program.objects.filter(
            white_label__code=p["white_label_code"],
            name_abbreviated=p["name_abbreviated"],
        ).first()

        if existing:
            program = existing
        else:
            program = Program.objects.new_program(
                white_label=p["white_label_code"],
                name_abbreviated=p["name_abbreviated"],
            )
            program.active = False
            program.has_calculator = False
            program.show_in_has_benefits_step = True
            program.base_program = p.get("base_program")
            program.save()

        # Always update translations — ensures correct text even if program was created
        # by an earlier version of this migration that lacked or had wrong translation calls.
        # Uses add_translation (not edit_translation) because add_translation explicitly calls
        # set_current_language() before saving, which is required for parler to write to the
        # correct language row. edit_translation skips that call and saves to whatever language
        # happens to be active at runtime (in a migration context: "en", not "en-us").
        Translation.objects.add_translation(
            f"program.{p['name_abbreviated']}_{program.id}-name",
            default_message=p["name_text"],
        )
        Translation.objects.add_translation(
            f"program.{p['name_abbreviated']}_{program.id}-description_short",
            default_message=p["description_text"],
        )
        Translation.objects.add_translation(
            f"program.{p['name_abbreviated']}_{program.id}-website_description",
            default_message=p["description_text"],
        )


def delete_tracking_programs(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    names = [p["name_abbreviated"] for p in TRACKING_PROGRAMS]
    Program.objects.filter(name_abbreviated__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0136_program_has_calculator_base_program"),
    ]

    operations = [
        migrations.RunPython(create_tracking_programs, delete_tracking_programs),
    ]
