# Generated by Django 4.2.22

from django.db import migrations

# Maps name_abbreviated → base_program for cross-WL grouping.
# Programs not in this dict get base_program=None (one-offs with no cross-WL equivalent).
NAME_TO_BASE_PROGRAM = {
    # SNAP
    "snap": "snap",
    "co_snap": "snap",
    "nc_snap": "snap",
    "il_snap": "snap",
    "tx_snap": "snap",
    "ma_snap": "snap",
    "cesn_snap": "snap",
    # TANF
    "tanf": "tanf",
    "co_tanf": "tanf",
    "nc_tanf": "tanf",
    "il_tanf": "tanf",
    "tx_tanf": "tanf",
    "ma_tafdc": "tanf",
    "cesn_tanf": "tanf",
    # WIC
    "wic": "wic",
    "co_wic": "wic",
    "nc_wic": "wic",
    "il_wic": "wic",
    "tx_wic": "wic",
    "ma_wic": "wic",
    "cesn_wic": "wic",
    # SSI
    "ssi": "ssi",
    "tx_ssi": "ssi",
    "cesn_ssi": "ssi",
    # SSDI
    "ssdi": "ssdi",
    "tx_ssdi": "ssdi",
    "cesn_ssdi": "ssdi",
    # Medicaid
    "co_medicaid": "medicaid",
    "cwd_medicaid": "medicaid",
    "emergency_medicaid": "medicaid",
    "awd_medicaid": "medicaid",
    "nc_medicaid": "medicaid",
    "nc_emergency_medicaid": "medicaid",
    "il_medicaid": "medicaid",
    "il_emergency_medicaid": "medicaid",
    "tx_emergency_medicaid": "medicaid",
    "tx_medicaid_for_parents_and_caretakers": "medicaid",
    "tx_medicaid_for_children": "medicaid",
    "tx_medicaid_for_pregnant_women": "medicaid",
    "ma_mass_health": "medicaid",
    "cesn_medicaid": "medicaid",
    "il_family_care": "medicaid",
    "il_moms_and_babies": "medicaid",
    "il_aca_adults": "medicaid",
    "il_all_kids": "medicaid",
    # ACA
    "nc_aca": "aca",
    "ma_aca": "aca",
    "tx_aca": "aca",
    # EITC
    "eitc": "eitc",
    "tx_eitc": "eitc",
    "coeitc": "eitc",
    "il_eitc": "eitc",
    "ma_maeitc": "eitc",
    # CTC
    "ctc": "ctc",
    "tx_ctc": "ctc",
    "il_ctc": "ctc",
    "coctc": "ctc",
    # NSLP
    "nslp": "nslp",
    "tx_nslp": "nslp",
    # NFP
    "co_nfp": "nfp",
    "il_nfp": "nfp",
    # Head Start
    "co_head_start": "head_start",
    "nc_head_start": "head_start",
    "ma_head_start": "head_start",
    "ma_early_head_start": "head_start",
    "tx_head_start": "head_start",
    "tx_early_head_start": "head_start",
    # Section 8
    "ma_cha": "section_8",
    "cesn_section_8": "section_8",
    # CSFP
    "il_csfp": "csfp",
    "tx_csfp": "csfp",
    "ma_csfp": "csfp",
    # Child Care
    "cccap": "child_care",
    "il_ccap": "child_care",
    "ma_ccdf": "child_care",
    "nc_scca": "child_care",
    "nc_cccap": "child_care",
    # Lifeline
    "lifeline": "lifeline",
    # CHP
    "chp": "chp",
    "cesn_chp": "chp",
    # OAP
    "oap": "oap",
    "cesn_oap": "oap",
    # Energy Assistance
    "leap": "energy_assistance",
    "cesn_leap": "energy_assistance",
    "nc_leap": "energy_assistance",
    "nc_lieap": "energy_assistance",
    "ma_heap": "energy_assistance",
    "il_liheap": "energy_assistance",
    "nccip": "energy_assistance",
    # Weatherization
    "cowap": "weatherization",
    "cesn_cowap": "weatherization",
    "ncwap": "weatherization",
    "tx_wap": "weatherization",
    # CCS
    "ccs": "ccs",
    "tx_ccs": "ccs",
    # Pell Grant
    "pell_grant": "pell_grant",
    # Sun Bucks
    "sunbucks": "sunbucks",
    # AND-CS
    "andcs": "andcs",
    "cesn_andcs": "andcs",
    # Medicare Savings
    "nc_medicare_savings": "medicare_savings",
    "medicare_savings": "medicare_savings",
}

# Programs that exist solely for tracking (no eligibility calculator).
# The tracking programs from 0137 are already has_calculator=False;
# this catches any other existing programs without calculators.
NO_CALCULATOR_PROGRAMS = [
    "cesn_snap",
    "cesn_tanf",
    "cesn_wic",
    "cesn_ssi",
    "cesn_ssdi",
    "cesn_chp",
    "cesn_oap",
    "cesn_section_8",
    "cesn_rtdlive",
    "cesn_andcs",
    "cesn_medicaid",
    "nc_leap",
    "nc_cccap",
    "co_andso",
    "co_care",
]


def backfill_base_program_and_has_calculator(apps, schema_editor):
    Program = apps.get_model("programs", "Program")

    # Backfill base_program
    for name_abbreviated, base_program in NAME_TO_BASE_PROGRAM.items():
        Program.objects.filter(name_abbreviated=name_abbreviated, base_program__isnull=True).update(
            base_program=base_program
        )

    # Ensure tracking-only programs have has_calculator=False
    Program.objects.filter(name_abbreviated__in=NO_CALCULATOR_PROGRAMS).update(has_calculator=False)


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0137_create_tracking_programs"),
    ]

    operations = [
        migrations.RunPython(backfill_base_program_and_has_calculator, migrations.RunPython.noop),
    ]
