# Generated by Django 4.2.22
#
# cocb (Colorado Cash Back) had its calculator deleted when the program was retired.
# The Program record is no longer needed.

from django.db import migrations


def delete_cocb(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    Program.objects.filter(name_abbreviated="cocb").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0138_backfill_has_calculator_base_program"),
    ]

    operations = [
        migrations.RunPython(delete_cocb, migrations.RunPython.noop),
    ]
