# Generated by Django 4.2.22 on 2026-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0139_delete_cocb_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="base_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aca", "ACA"),
                    ("ccap", "CCAP"),
                    ("chp", "CHP"),
                    ("csfp", "CSFP"),
                    ("ctc", "CTC"),
                    ("early_head_start", "Early Head Start"),
                    ("eitc", "EITC"),
                    ("head_start", "Head Start"),
                    ("liheap", "LIHEAP"),
                    ("lifeline", "Lifeline"),
                    ("medicaid", "Medicaid"),
                    ("medicare_savings", "Medicare Savings"),
                    ("nfp", "NFP"),
                    ("nslp", "NSLP"),
                    ("oap", "OAP"),
                    ("section_8", "Section 8"),
                    ("snap", "SNAP"),
                    ("ssi", "SSI"),
                    ("ssdi", "SSDI"),
                    ("tanf", "TANF"),
                    ("wap", "WAP"),
                    ("wic", "WIC"),
                ],
                help_text="Cross-white-label program grouping for analytics (e.g. co_snap, il_snap → snap)",
                max_length=32,
                null=True,
            ),
        ),
    ]
