# Generated by Django 4.2.22

from django.db import migrations


def rename_cesn_cowap_to_cesn_wap(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    Program.objects.filter(name_abbreviated="cesn_cowap").update(
        name_abbreviated="cesn_wap", external_name="cesn_wap"
    )


def rename_cesn_wap_to_cesn_cowap(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    Program.objects.filter(name_abbreviated="cesn_wap").update(
        name_abbreviated="cesn_cowap", external_name="cesn_cowap"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0139_delete_cocb_program"),
    ]

    operations = [
        migrations.RunPython(rename_cesn_cowap_to_cesn_wap, rename_cesn_wap_to_cesn_cowap),
    ]
