# Generated by Django 4.2.22 on 2026-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0150_backfill_screen_current_benefits"),
        ("programs", "0140_update_base_program_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="referrer",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="referrer",
            name="show_in_dropdown",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="referrer",
            name="referrer_code",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="referrer",
            unique_together={("white_label", "referrer_code")},
        ),
    ]
