# Generated by Django 4.2.22 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0144_alter_program_base_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigator",
            name="eligibility_programs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Navigator is only shown when the household qualifies for ALL of these programs.",
                related_name="eligibility_navigators",
                to="programs.program",
            ),
        ),
    ]
