# Generated by Django 4.2.22 on 2026-04-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0141_add_referrer_name_dropdown_and_per_wl_uniqueness"),
        ("programs", "0145_seed_referrer_rows_from_referral_options"),
    ]

    operations = []
