# Generated by Django 4.2.22 on 2026-04-16 18:15

from django.db import migrations


def add_flyers_translation(apps, schema_editor):
    from translations.models import Translation

    Translation.objects.add_translation(
        "referralOptions.flyers",
        default_message="Flyer",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0146_merge_20260415_1624"),
        ("translations", "0006_move_zh_data"),
    ]

    operations = [
        migrations.RunPython(add_flyers_translation, migrations.RunPython.noop),
    ]
