# Generated by Django 4.2.22 on 2026-04-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0140_alter_program_base_program_and_more"),
        ("programs", "0147_add_flyers_referral_option_translation"),
    ]

    operations = []
