# Generated by Django 4.2.22 on 2026-04-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0147_add_flyers_referral_option_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="external_name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
