# Generated by Django 4.2.28 on 2026-04-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0148_navigator_eligibility_programs"),
        ("programs", "0150_backfill_program_value_type"),
    ]

    operations = []
