# Generated by Django 4.2.28 on 2026-06-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0155_assign_year"),
        ("programs", "0156_deactivate_co_my_spark"),
    ]

    operations = []
