# Generated by Django 4.2.28 on 2026-06-09 18:58

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0157_consolidate_nc_categories"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="program",
            constraint=models.CheckConstraint(
                check=models.Q(("name_abbreviated", django.db.models.functions.text.Lower("name_abbreviated"))),
                name="program_name_abbreviated_lowercase",
            ),
        ),
    ]
