# Generated by Django 4.2.28 on 2026-06-29 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0157_drop_has_columns'),
        ('translations', '0006_move_zh_data'),
        ('programs', '0159_seed_ks_generic_referrers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lucide_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('condition', 'Condition'), ('health_insurance', 'Health Insurance'), ('referral', 'Referral Source')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.icon')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.translation')),
                ('white_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_options', to='screener.whitelabel')),
            ],
            options={
                'ordering': ['white_label', 'option_type', 'order'],
                'indexes': [models.Index(fields=['white_label', 'option_type'], name='programs_fo_white_l_c9dbb5_idx')],
                'unique_together': {('white_label', 'option_type', 'value')},
            },
        ),
    ]
