# Generated by Django 4.2.22 on 2026-06-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0159_seed_ks_generic_referrers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="value_type",
        ),
    ]
