# Generated by Django 4.2.28 on 2026-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0157_drop_has_columns'),
        ('programs', '0160_add_icon_and_form_option_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formoption',
            options={'ordering': ['white_label', 'option_type', 'person', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='formoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='formoption',
            name='person',
            field=models.CharField(choices=[('you', 'You'), ('them', 'Them'), ('all', 'All')], default='all', max_length=4),
        ),
        migrations.AlterField(
            model_name='formoption',
            name='option_type',
            field=models.CharField(choices=[('acute_condition', 'Acute Condition'), ('condition', 'Condition'), ('health_insurance', 'Health Insurance')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='formoption',
            unique_together={('white_label', 'option_type', 'person', 'value')},
        ),
    ]
