# Generated by Django 4.2.28 on 2026-07-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0161_delete_ubp_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='base_program',
            field=models.CharField(blank=True, choices=[('aca', 'ACA'), ('ccap', 'CCAP'), ('cdcc', 'CDCC'), ('chp', 'CHP'), ('csfp', 'CSFP'), ('ctc', 'CTC'), ('early_head_start', 'Early Head Start'), ('eitc', 'EITC'), ('head_start', 'Head Start'), ('liheap', 'LIHEAP'), ('lifeline', 'Lifeline'), ('medicaid', 'Medicaid'), ('medicare_savings', 'Medicare Savings'), ('nfp', 'NFP'), ('nslp', 'NSLP'), ('oap', 'OAP'), ('section_8', 'Section 8'), ('snap', 'SNAP'), ('ssi', 'SSI'), ('ssdi', 'SSDI'), ('tanf', 'TANF'), ('wap', 'WAP'), ('wic', 'WIC')], help_text='Cross-white-label program grouping for analytics (e.g. co_snap, il_snap → snap)', max_length=32, null=True),
        ),
    ]
