# Generated by Django 4.2.28 on 2026-09-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0161_screen_needs_medical_expenses_and_debt'),
        ('programs', '0170_deactivate_il_rent_asst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcategory',
            name='white_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_categories', to='screener.whitelabel'),
        ),
    ]
